export interface MonumentDef {
  id: string;
  name: string;
  country: string;
  region: string;
  /** Path under /public to a real photo of the monument. */
  image: string;
}

export const MONUMENTS: MonumentDef[] = [
  // Asia
  { id: "taj-mahal", name: "Taj Mahal", country: "India", region: "Asia", image: "/monuments/taj-mahal.jpg" },
  { id: "great-wall", name: "The Great Wall", country: "China", region: "Asia", image: "/monuments/great-wall.jpg" },
  { id: "angkor-wat", name: "Angkor Wat", country: "Cambodia", region: "Asia", image: "/monuments/angkor-wat.jpg" },
  { id: "mount-fuji", name: "Mount Fuji", country: "Japan", region: "Asia", image: "/monuments/mount-fuji.jpg" },
  { id: "borobudur", name: "Borobudur", country: "Indonesia", region: "Asia", image: "/monuments/borobudur.jpg" },
  { id: "forbidden-city", name: "The Forbidden City", country: "China", region: "Asia", image: "/monuments/forbidden-city.jpg" },
  { id: "himeji-castle", name: "Himeji Castle", country: "Japan", region: "Asia", image: "/monuments/himeji-castle.jpg" },
  { id: "potala-palace", name: "Potala Palace", country: "China", region: "Asia", image: "/monuments/potala-palace.jpg" },
  { id: "shwedagon", name: "Shwedagon Pagoda", country: "Myanmar", region: "Asia", image: "/monuments/shwedagon.jpg" },
  { id: "meenakshi-temple", name: "Meenakshi Temple", country: "India", region: "Asia", image: "/monuments/meenakshi-temple.jpg" },
  { id: "terracotta-army", name: "The Terracotta Army", country: "China", region: "Asia", image: "/monuments/terracotta-army.jpg" },
  { id: "summer-palace", name: "The Summer Palace", country: "China", region: "Asia", image: "/monuments/summer-palace.jpg" },
  { id: "temple-of-heaven", name: "The Temple of Heaven", country: "China", region: "Asia", image: "/monuments/temple-of-heaven.jpg" },
  { id: "zhangjiajie", name: "Zhangjiajie National Forest Park", country: "China", region: "Asia", image: "/monuments/zhangjiajie.jpg" },
  { id: "li-river", name: "The Li River", country: "China", region: "Asia", image: "/monuments/li-river.jpg" },
  { id: "shibuya-crossing", name: "Shibuya Crossing", country: "Japan", region: "Asia", image: "/monuments/shibuya-crossing.jpg" },
  { id: "tokyo-tower", name: "Tokyo Tower", country: "Japan", region: "Asia", image: "/monuments/tokyo-tower.jpg" },
  { id: "fushimi-inari", name: "Fushimi Inari Shrine", country: "Japan", region: "Asia", image: "/monuments/fushimi-inari.jpg" },
  { id: "kinkaku-ji", name: "Kinkaku-ji (The Golden Pavilion)", country: "Japan", region: "Asia", image: "/monuments/kinkaku-ji.jpg" },
  { id: "osaka-castle", name: "Osaka Castle", country: "Japan", region: "Asia", image: "/monuments/osaka-castle.jpg" },
  { id: "mount-bromo", name: "Mount Bromo", country: "Indonesia", region: "Asia", image: "/monuments/mount-bromo.jpg" },
  { id: "komodo-national-park", name: "Komodo National Park", country: "Indonesia", region: "Asia", image: "/monuments/komodo-national-park.jpg" },
  { id: "ha-long-bay", name: "Ha Long Bay", country: "Vietnam", region: "Asia", image: "/monuments/ha-long-bay.jpg" },
  { id: "hoi-an", name: "Hoi An Ancient Town", country: "Vietnam", region: "Asia", image: "/monuments/hoi-an.jpg" },
  { id: "wat-arun", name: "Wat Arun", country: "Thailand", region: "Asia", image: "/monuments/wat-arun.jpg" },
  { id: "grand-palace-bangkok", name: "The Grand Palace", country: "Thailand", region: "Asia", image: "/monuments/grand-palace-bangkok.jpg" },
  { id: "gyeongbokgung", name: "Gyeongbokgung Palace", country: "South Korea", region: "Asia", image: "/monuments/gyeongbokgung.jpg" },
  { id: "n-seoul-tower", name: "N Seoul Tower", country: "South Korea", region: "Asia", image: "/monuments/n-seoul-tower.jpg" },
  { id: "marina-bay-sands", name: "Marina Bay Sands", country: "Singapore", region: "Asia", image: "/monuments/marina-bay-sands.jpg" },
  { id: "gardens-by-the-bay", name: "Gardens by the Bay", country: "Singapore", region: "Asia", image: "/monuments/gardens-by-the-bay.jpg" },
  { id: "petronas-towers", name: "The Petronas Towers", country: "Malaysia", region: "Asia", image: "/monuments/petronas-towers.jpg" },
  { id: "chocolate-hills", name: "The Chocolate Hills", country: "Philippines", region: "Asia", image: "/monuments/chocolate-hills.jpg" },
  { id: "jaisalmer-fort", name: "Jaisalmer Fort", country: "India", region: "Asia", image: "/monuments/jaisalmer-fort.jpg" },
  { id: "hawa-mahal", name: "Hawa Mahal", country: "India", region: "Asia", image: "/monuments/hawa-mahal.jpg" },
  { id: "amber-fort", name: "Amber Fort", country: "India", region: "Asia", image: "/monuments/amber-fort.jpg" },
  { id: "varanasi-ghats", name: "The Ghats of Varanasi", country: "India", region: "Asia", image: "/monuments/varanasi-ghats.jpg" },
  { id: "everest-base-camp", name: "Mount Everest", country: "Nepal", region: "Asia", image: "/monuments/everest-base-camp.jpg" },

  // Middle East
  { id: "petra", name: "Petra", country: "Jordan", region: "Middle East", image: "/monuments/petra.jpg" },
  { id: "dome-of-the-rock", name: "Dome of the Rock", country: "Jerusalem", region: "Middle East", image: "/monuments/dome-of-the-rock.jpg" },
  { id: "burj-khalifa", name: "Burj Khalifa", country: "United Arab Emirates", region: "Middle East", image: "/monuments/burj-khalifa.jpg" },
  { id: "sheikh-zayed-mosque", name: "Sheikh Zayed Mosque", country: "United Arab Emirates", region: "Middle East", image: "/monuments/sheikh-zayed-mosque.jpg" },
  { id: "persepolis", name: "Persepolis", country: "Iran", region: "Middle East", image: "/monuments/persepolis.jpg" },
  { id: "blue-mosque", name: "The Blue Mosque", country: "Turkey", region: "Middle East", image: "/monuments/blue-mosque.jpg" },
  { id: "hagia-sophia", name: "Hagia Sophia", country: "Turkey", region: "Middle East", image: "/monuments/hagia-sophia.jpg" },
  { id: "cappadocia", name: "Cappadocia", country: "Turkey", region: "Middle East", image: "/monuments/cappadocia.jpg" },
  { id: "pamukkale", name: "Pamukkale", country: "Turkey", region: "Middle East", image: "/monuments/pamukkale.jpg" },
  { id: "western-wall", name: "The Western Wall", country: "Jerusalem", region: "Middle East", image: "/monuments/western-wall.jpg" },
  { id: "palmyra", name: "Palmyra", country: "Syria", region: "Middle East", image: "/monuments/palmyra.jpg" },
  { id: "palm-jumeirah", name: "Palm Jumeirah", country: "United Arab Emirates", region: "Middle East", image: "/monuments/palm-jumeirah.jpg" },
  { id: "dubai-frame", name: "The Dubai Frame", country: "United Arab Emirates", region: "Middle East", image: "/monuments/dubai-frame.jpg" },
  { id: "wadi-rum", name: "Wadi Rum", country: "Jordan", region: "Middle East", image: "/monuments/wadi-rum.jpg" },
  { id: "jeita-grotto", name: "Jeita Grotto", country: "Lebanon", region: "Middle East", image: "/monuments/jeita-grotto.jpg" },
  { id: "baalbek", name: "Baalbek", country: "Lebanon", region: "Middle East", image: "/monuments/baalbek.jpg" },
  { id: "museum-of-islamic-art-doha", name: "The Museum of Islamic Art", country: "Qatar", region: "Middle East", image: "/monuments/museum-of-islamic-art-doha.jpg" },

  // Europe
  { id: "eiffel-tower", name: "The Eiffel Tower", country: "France", region: "Europe", image: "/monuments/eiffel-tower.jpg" },
  { id: "colosseum", name: "The Colosseum", country: "Italy", region: "Europe", image: "/monuments/colosseum.jpg" },
  { id: "big-ben", name: "Big Ben", country: "United Kingdom", region: "Europe", image: "/monuments/big-ben.jpg" },
  { id: "neuschwanstein", name: "Neuschwanstein Castle", country: "Germany", region: "Europe", image: "/monuments/neuschwanstein.jpg" },
  { id: "sagrada-familia", name: "The Sagrada Familia", country: "Spain", region: "Europe", image: "/monuments/sagrada-familia.jpg" },
  { id: "acropolis", name: "The Acropolis", country: "Greece", region: "Europe", image: "/monuments/acropolis.jpg" },
  { id: "stonehenge", name: "Stonehenge", country: "United Kingdom", region: "Europe", image: "/monuments/stonehenge.jpg" },
  { id: "pisa-tower", name: "The Leaning Tower of Pisa", country: "Italy", region: "Europe", image: "/monuments/pisa-tower.jpg" },
  { id: "arc-de-triomphe", name: "The Arc de Triomphe", country: "France", region: "Europe", image: "/monuments/arc-de-triomphe.jpg" },
  { id: "st-basils", name: "St. Basil's Cathedral", country: "Russia", region: "Europe", image: "/monuments/st-basils.jpg" },
  { id: "louvre", name: "The Louvre", country: "France", region: "Europe", image: "/monuments/louvre.jpg" },
  { id: "notre-dame", name: "Notre-Dame Cathedral", country: "France", region: "Europe", image: "/monuments/notre-dame.jpg" },
  { id: "mont-saint-michel", name: "Mont Saint-Michel", country: "France", region: "Europe", image: "/monuments/mont-saint-michel.jpg" },
  { id: "versailles", name: "The Palace of Versailles", country: "France", region: "Europe", image: "/monuments/versailles.jpg" },
  { id: "brandenburg-gate", name: "The Brandenburg Gate", country: "Germany", region: "Europe", image: "/monuments/brandenburg-gate.jpg" },
  { id: "cologne-cathedral", name: "Cologne Cathedral", country: "Germany", region: "Europe", image: "/monuments/cologne-cathedral.jpg" },
  { id: "berlin-wall", name: "The East Side Gallery", country: "Germany", region: "Europe", image: "/monuments/berlin-wall.jpg" },
  { id: "venice-canals", name: "The Grand Canal", country: "Italy", region: "Europe", image: "/monuments/venice-canals.jpg" },
  { id: "trevi-fountain", name: "The Trevi Fountain", country: "Italy", region: "Europe", image: "/monuments/trevi-fountain.jpg" },
  { id: "milan-cathedral", name: "Milan Cathedral", country: "Italy", region: "Europe", image: "/monuments/milan-cathedral.jpg" },
  { id: "st-peters-basilica", name: "St. Peter's Basilica", country: "Vatican City", region: "Europe", image: "/monuments/st-peters-basilica.jpg" },
  { id: "amalfi-coast", name: "The Amalfi Coast", country: "Italy", region: "Europe", image: "/monuments/amalfi-coast.jpg" },
  { id: "cinque-terre", name: "Cinque Terre", country: "Italy", region: "Europe", image: "/monuments/cinque-terre.jpg" },
  { id: "alhambra", name: "The Alhambra", country: "Spain", region: "Europe", image: "/monuments/alhambra.jpg" },
  { id: "park-guell", name: "Park Güell", country: "Spain", region: "Europe", image: "/monuments/park-guell.jpg" },
  { id: "santorini", name: "Santorini", country: "Greece", region: "Europe", image: "/monuments/santorini.jpg" },
  { id: "meteora", name: "Meteora", country: "Greece", region: "Europe", image: "/monuments/meteora.jpg" },
  { id: "buckingham-palace", name: "Buckingham Palace", country: "United Kingdom", region: "Europe", image: "/monuments/buckingham-palace.jpg" },
  { id: "tower-bridge", name: "Tower Bridge", country: "United Kingdom", region: "Europe", image: "/monuments/tower-bridge.jpg" },
  { id: "tower-of-london", name: "The Tower of London", country: "United Kingdom", region: "Europe", image: "/monuments/tower-of-london.jpg" },
  { id: "edinburgh-castle", name: "Edinburgh Castle", country: "United Kingdom", region: "Europe", image: "/monuments/edinburgh-castle.jpg" },
  { id: "giants-causeway", name: "The Giant's Causeway", country: "United Kingdom", region: "Europe", image: "/monuments/giants-causeway.jpg" },
  { id: "cliffs-of-moher", name: "The Cliffs of Moher", country: "Ireland", region: "Europe", image: "/monuments/cliffs-of-moher.jpg" },
  { id: "kinderdijk-windmills", name: "The Windmills of Kinderdijk", country: "Netherlands", region: "Europe", image: "/monuments/kinderdijk-windmills.jpg" },
  { id: "amsterdam-canals", name: "The Canals of Amsterdam", country: "Netherlands", region: "Europe", image: "/monuments/amsterdam-canals.jpg" },
  { id: "charles-bridge", name: "Charles Bridge", country: "Czech Republic", region: "Europe", image: "/monuments/charles-bridge.jpg" },
  { id: "prague-castle", name: "Prague Castle", country: "Czech Republic", region: "Europe", image: "/monuments/prague-castle.jpg" },
  { id: "schonbrunn-palace", name: "Schönbrunn Palace", country: "Austria", region: "Europe", image: "/monuments/schonbrunn-palace.jpg" },
  { id: "hallstatt", name: "Hallstatt", country: "Austria", region: "Europe", image: "/monuments/hallstatt.jpg" },
  { id: "matterhorn", name: "The Matterhorn", country: "Switzerland", region: "Europe", image: "/monuments/matterhorn.jpg" },
  { id: "plitvice-lakes", name: "Plitvice Lakes", country: "Croatia", region: "Europe", image: "/monuments/plitvice-lakes.jpg" },
  { id: "dubrovnik-old-town", name: "Dubrovnik Old Town", country: "Croatia", region: "Europe", image: "/monuments/dubrovnik-old-town.jpg" },
  { id: "sintra-pena-palace", name: "Pena Palace", country: "Portugal", region: "Europe", image: "/monuments/sintra-pena-palace.jpg" },
  { id: "belem-tower", name: "Belém Tower", country: "Portugal", region: "Europe", image: "/monuments/belem-tower.jpg" },
  { id: "moscow-kremlin", name: "The Moscow Kremlin", country: "Russia", region: "Europe", image: "/monuments/moscow-kremlin.jpg" },
  { id: "lake-bled", name: "Lake Bled", country: "Slovenia", region: "Europe", image: "/monuments/lake-bled.jpg" },

  // Africa
  { id: "pyramids-giza", name: "The Pyramids of Giza", country: "Egypt", region: "Africa", image: "/monuments/pyramids-giza.jpg" },
  { id: "sphinx", name: "The Great Sphinx", country: "Egypt", region: "Africa", image: "/monuments/sphinx.jpg" },
  { id: "table-mountain", name: "Table Mountain", country: "South Africa", region: "Africa", image: "/monuments/table-mountain.jpg" },
  { id: "victoria-falls", name: "Victoria Falls", country: "Zambia", region: "Africa", image: "/monuments/victoria-falls.jpg" },
  { id: "djenne-mosque", name: "The Great Mosque of Djenné", country: "Mali", region: "Africa", image: "/monuments/djenne-mosque.jpg" },
  { id: "lalibela", name: "The Rock Churches of Lalibela", country: "Ethiopia", region: "Africa", image: "/monuments/lalibela.jpg" },
  { id: "karnak-temple", name: "The Karnak Temple", country: "Egypt", region: "Africa", image: "/monuments/karnak-temple.jpg" },
  { id: "valley-of-the-kings", name: "The Valley of the Kings", country: "Egypt", region: "Africa", image: "/monuments/valley-of-the-kings.jpg" },
  { id: "abu-simbel", name: "The Abu Simbel Temples", country: "Egypt", region: "Africa", image: "/monuments/abu-simbel.jpg" },
  { id: "serengeti", name: "The Serengeti", country: "Tanzania", region: "Africa", image: "/monuments/serengeti.jpg" },
  { id: "ngorongoro-crater", name: "The Ngorongoro Crater", country: "Tanzania", region: "Africa", image: "/monuments/ngorongoro-crater.jpg" },
  { id: "mount-kilimanjaro", name: "Mount Kilimanjaro", country: "Tanzania", region: "Africa", image: "/monuments/mount-kilimanjaro.jpg" },
  { id: "maasai-mara", name: "The Maasai Mara", country: "Kenya", region: "Africa", image: "/monuments/maasai-mara.jpg" },
  { id: "sahara-desert", name: "The Sahara Desert", country: "Morocco", region: "Africa", image: "/monuments/sahara-desert.jpg" },
  { id: "chefchaouen", name: "Chefchaouen", country: "Morocco", region: "Africa", image: "/monuments/chefchaouen.jpg" },
  { id: "jemaa-el-fnaa", name: "Jemaa el-Fnaa", country: "Morocco", region: "Africa", image: "/monuments/jemaa-el-fnaa.jpg" },
  { id: "hassan-ii-mosque", name: "The Hassan II Mosque", country: "Morocco", region: "Africa", image: "/monuments/hassan-ii-mosque.jpg" },
  { id: "cape-of-good-hope", name: "The Cape of Good Hope", country: "South Africa", region: "Africa", image: "/monuments/cape-of-good-hope.jpg" },
  { id: "robben-island", name: "Robben Island", country: "South Africa", region: "Africa", image: "/monuments/robben-island.jpg" },
  { id: "okavango-delta", name: "The Okavango Delta", country: "Botswana", region: "Africa", image: "/monuments/okavango-delta.jpg" },
  { id: "zanzibar-stone-town", name: "Stone Town", country: "Tanzania", region: "Africa", image: "/monuments/zanzibar-stone-town.jpg" },
  { id: "namib-desert", name: "The Namib Desert", country: "Namibia", region: "Africa", image: "/monuments/namib-desert.jpg" },

  // Americas
  { id: "statue-of-liberty", name: "The Statue of Liberty", country: "United States", region: "Americas", image: "/monuments/statue-of-liberty.jpg" },
  { id: "christ-redeemer", name: "Christ the Redeemer", country: "Brazil", region: "Americas", image: "/monuments/christ-redeemer.jpg" },
  { id: "machu-picchu", name: "Machu Picchu", country: "Peru", region: "Americas", image: "/monuments/machu-picchu.jpg" },
  { id: "chichen-itza", name: "Chichen Itza", country: "Mexico", region: "Americas", image: "/monuments/chichen-itza.jpg" },
  { id: "golden-gate", name: "The Golden Gate Bridge", country: "United States", region: "Americas", image: "/monuments/golden-gate.jpg" },
  { id: "gateway-arch", name: "The Gateway Arch", country: "United States", region: "Americas", image: "/monuments/gateway-arch.jpg" },
  { id: "cn-tower", name: "The CN Tower", country: "Canada", region: "Americas", image: "/monuments/cn-tower.jpg" },
  { id: "niagara-falls", name: "Niagara Falls", country: "Canada", region: "Americas", image: "/monuments/niagara-falls.jpg" },
  { id: "moai", name: "The Moai of Easter Island", country: "Chile", region: "Americas", image: "/monuments/moai.jpg" },
  { id: "teotihuacan", name: "Teotihuacan", country: "Mexico", region: "Americas", image: "/monuments/teotihuacan.jpg" },
  { id: "grand-canyon", name: "The Grand Canyon", country: "United States", region: "Americas", image: "/monuments/grand-canyon.jpg" },
  { id: "yellowstone", name: "Yellowstone National Park", country: "United States", region: "Americas", image: "/monuments/yellowstone.jpg" },
  { id: "mount-rushmore", name: "Mount Rushmore", country: "United States", region: "Americas", image: "/monuments/mount-rushmore.jpg" },
  { id: "hollywood-sign", name: "The Hollywood Sign", country: "United States", region: "Americas", image: "/monuments/hollywood-sign.jpg" },
  { id: "times-square", name: "Times Square", country: "United States", region: "Americas", image: "/monuments/times-square.jpg" },
  { id: "las-vegas-strip", name: "The Las Vegas Strip", country: "United States", region: "Americas", image: "/monuments/las-vegas-strip.jpg" },
  { id: "white-house", name: "The White House", country: "United States", region: "Americas", image: "/monuments/white-house.jpg" },
  { id: "lincoln-memorial", name: "The Lincoln Memorial", country: "United States", region: "Americas", image: "/monuments/lincoln-memorial.jpg" },
  { id: "empire-state-building", name: "The Empire State Building", country: "United States", region: "Americas", image: "/monuments/empire-state-building.jpg" },
  { id: "brooklyn-bridge", name: "The Brooklyn Bridge", country: "United States", region: "Americas", image: "/monuments/brooklyn-bridge.jpg" },
  { id: "hoover-dam", name: "The Hoover Dam", country: "United States", region: "Americas", image: "/monuments/hoover-dam.jpg" },
  { id: "yosemite", name: "Yosemite National Park", country: "United States", region: "Americas", image: "/monuments/yosemite.jpg" },
  { id: "antelope-canyon", name: "Antelope Canyon", country: "United States", region: "Americas", image: "/monuments/antelope-canyon.jpg" },
  { id: "metropolitan-museum", name: "The Metropolitan Museum of Art", country: "United States", region: "Americas", image: "/monuments/metropolitan-museum.jpg" },
  { id: "space-needle", name: "The Space Needle", country: "United States", region: "Americas", image: "/monuments/space-needle.jpg" },
  { id: "alcatraz", name: "Alcatraz Island", country: "United States", region: "Americas", image: "/monuments/alcatraz.jpg" },
  { id: "washington-monument", name: "The Washington Monument", country: "United States", region: "Americas", image: "/monuments/washington-monument.jpg" },
  { id: "one-world-trade-center", name: "One World Trade Center", country: "United States", region: "Americas", image: "/monuments/one-world-trade-center.jpg" },
  { id: "chicago-bean", name: "Cloud Gate", country: "United States", region: "Americas", image: "/monuments/chicago-bean.jpg" },
  { id: "french-quarter-new-orleans", name: "The French Quarter", country: "United States", region: "Americas", image: "/monuments/french-quarter-new-orleans.jpg" },
  { id: "banff-national-park", name: "Banff National Park", country: "Canada", region: "Americas", image: "/monuments/banff-national-park.jpg" },
  { id: "lake-louise", name: "Lake Louise", country: "Canada", region: "Americas", image: "/monuments/lake-louise.jpg" },
  { id: "tulum", name: "Tulum", country: "Mexico", region: "Americas", image: "/monuments/tulum.jpg" },
  { id: "iguazu-falls", name: "Iguazu Falls", country: "Brazil", region: "Americas", image: "/monuments/iguazu-falls.jpg" },
  { id: "copacabana-beach", name: "Copacabana Beach", country: "Brazil", region: "Americas", image: "/monuments/copacabana-beach.jpg" },
  { id: "amazon-rainforest", name: "The Amazon Rainforest", country: "Brazil", region: "Americas", image: "/monuments/amazon-rainforest.jpg" },
  { id: "salar-de-uyuni", name: "Salar de Uyuni", country: "Bolivia", region: "Americas", image: "/monuments/salar-de-uyuni.jpg" },
  { id: "galapagos-islands", name: "The Galápagos Islands", country: "Ecuador", region: "Americas", image: "/monuments/galapagos-islands.jpg" },
  { id: "cartagena-old-town", name: "Cartagena's Old Town", country: "Colombia", region: "Americas", image: "/monuments/cartagena-old-town.jpg" },
  { id: "torres-del-paine", name: "Torres del Paine", country: "Chile", region: "Americas", image: "/monuments/torres-del-paine.jpg" },
  { id: "perito-moreno-glacier", name: "The Perito Moreno Glacier", country: "Argentina", region: "Americas", image: "/monuments/perito-moreno-glacier.jpg" },
  { id: "obelisco-buenos-aires", name: "The Obelisco de Buenos Aires", country: "Argentina", region: "Americas", image: "/monuments/obelisco-buenos-aires.jpg" },
  { id: "havana-old-town", name: "Old Havana", country: "Cuba", region: "Americas", image: "/monuments/havana-old-town.jpg" },
  { id: "panama-canal", name: "The Panama Canal", country: "Panama", region: "Americas", image: "/monuments/panama-canal.jpg" },

  // Oceania
  { id: "sydney-opera-house", name: "The Sydney Opera House", country: "Australia", region: "Oceania", image: "/monuments/sydney-opera-house.jpg" },
  { id: "sydney-harbour-bridge", name: "The Sydney Harbour Bridge", country: "Australia", region: "Oceania", image: "/monuments/sydney-harbour-bridge.jpg" },
  { id: "uluru", name: "Uluru", country: "Australia", region: "Oceania", image: "/monuments/uluru.jpg" },
  { id: "sky-tower", name: "The Sky Tower", country: "New Zealand", region: "Oceania", image: "/monuments/sky-tower.jpg" },
  { id: "great-barrier-reef", name: "The Great Barrier Reef", country: "Australia", region: "Oceania", image: "/monuments/great-barrier-reef.jpg" },
  { id: "bondi-beach", name: "Bondi Beach", country: "Australia", region: "Oceania", image: "/monuments/bondi-beach.jpg" },
  { id: "twelve-apostles", name: "The Twelve Apostles", country: "Australia", region: "Oceania", image: "/monuments/twelve-apostles.jpg" },
  { id: "kata-tjuta", name: "Kata Tjuta", country: "Australia", region: "Oceania", image: "/monuments/kata-tjuta.jpg" },
  { id: "daintree-rainforest", name: "The Daintree Rainforest", country: "Australia", region: "Oceania", image: "/monuments/daintree-rainforest.jpg" },
  { id: "milford-sound", name: "Milford Sound", country: "New Zealand", region: "Oceania", image: "/monuments/milford-sound.jpg" },
  { id: "tongariro-national-park", name: "Tongariro National Park", country: "New Zealand", region: "Oceania", image: "/monuments/tongariro-national-park.jpg" },
  { id: "waitomo-glowworm-caves", name: "The Waitomo Glowworm Caves", country: "New Zealand", region: "Oceania", image: "/monuments/waitomo-glowworm-caves.jpg" },
  { id: "hobbiton", name: "Hobbiton Movie Set", country: "New Zealand", region: "Oceania", image: "/monuments/hobbiton.jpg" },
  { id: "bora-bora", name: "Bora Bora", country: "French Polynesia", region: "Oceania", image: "/monuments/bora-bora.jpg" },
];

export function monumentById(id: string): MonumentDef | undefined {
  return MONUMENTS.find((m) => m.id === id);
}

export const UPLIFTING_QUOTES: string[] = [
  "Some things take time to come together — and that's exactly as it should be.",
  "Every piece you place is still progress, even the ones that take a few tries.",
  "There's no rush here. The view is just as beautiful at your own pace.",
  "What looks scattered now is closer to whole than you think.",
  "Patience isn't waiting — it's building something worth seeing.",
  "You don't have to rush toward finished. Finished will meet you when it's ready.",
  "Small, steady moves are still the ones that build something lasting.",
  "It's okay if it takes longer than you expected. It still came together.",
  "Some of the best things in the world were built one careful piece at a time.",
  "You showed up for something slow and quiet today. That counts for a lot.",
  "A little bit of care, placed again and again, becomes something whole.",
  "Nothing here was rushed, and neither should you be.",
  "The pieces fit eventually. They always do, when you give them room to.",
  "You didn't need to be fast. You only needed to keep going.",
  "This came together because you were willing to sit with it a while.",
  "Not every kind of progress feels urgent — some of it just feels peaceful.",
  "You built this the same way most good things get built: slowly, and on purpose.",
  "Take a breath. What you just finished, you finished at exactly the right pace.",
  "It's a good kind of quiet, the one that comes after finishing something gently.",
  "Some journeys are measured in miles. Others, in pieces fit together with care.",
];

export function randomQuote(): string {
  return UPLIFTING_QUOTES[Math.floor(Math.random() * UPLIFTING_QUOTES.length)];
}
