export interface MonumentDef {
  id: string;
  name: string;
  country: string;
  region: string;
  /** Path under /public to a real photo of the monument. */
  image: string;
}

export const MONUMENTS: MonumentDef[] = [
  // Asia
  { id: "taj-mahal", name: "Taj Mahal", country: "India", region: "Asia", image: "/monuments/taj-mahal.jpg" },
  { id: "great-wall", name: "The Great Wall", country: "China", region: "Asia", image: "/monuments/great-wall.jpg" },
  { id: "angkor-wat", name: "Angkor Wat", country: "Cambodia", region: "Asia", image: "/monuments/angkor-wat.jpg" },
  { id: "mount-fuji", name: "Mount Fuji", country: "Japan", region: "Asia", image: "/monuments/mount-fuji.jpg" },
  { id: "borobudur", name: "Borobudur", country: "Indonesia", region: "Asia", image: "/monuments/borobudur.jpg" },
  { id: "forbidden-city", name: "The Forbidden City", country: "China", region: "Asia", image: "/monuments/forbidden-city.jpg" },
  { id: "himeji-castle", name: "Himeji Castle", country: "Japan", region: "Asia", image: "/monuments/himeji-castle.jpg" },
  { id: "potala-palace", name: "Potala Palace", country: "China", region: "Asia", image: "/monuments/potala-palace.jpg" },
  { id: "shwedagon", name: "Shwedagon Pagoda", country: "Myanmar", region: "Asia", image: "/monuments/shwedagon.jpg" },
  { id: "meenakshi-temple", name: "Meenakshi Temple", country: "India", region: "Asia", image: "/monuments/meenakshi-temple.jpg" },
  { id: "terracotta-army", name: "The Terracotta Army", country: "China", region: "Asia", image: "/monuments/terracotta-army.jpg" },
  { id: "summer-palace", name: "The Summer Palace", country: "China", region: "Asia", image: "/monuments/summer-palace.jpg" },
  { id: "temple-of-heaven", name: "The Temple of Heaven", country: "China", region: "Asia", image: "/monuments/temple-of-heaven.jpg" },
  { id: "zhangjiajie", name: "Zhangjiajie National Forest Park", country: "China", region: "Asia", image: "/monuments/zhangjiajie.jpg" },
  { id: "li-river", name: "The Li River", country: "China", region: "Asia", image: "/monuments/li-river.jpg" },
  { id: "shibuya-crossing", name: "Shibuya Crossing", country: "Japan", region: "Asia", image: "/monuments/shibuya-crossing.jpg" },
  { id: "tokyo-tower", name: "Tokyo Tower", country: "Japan", region: "Asia", image: "/monuments/tokyo-tower.jpg" },
  { id: "fushimi-inari", name: "Fushimi Inari Shrine", country: "Japan", region: "Asia", image: "/monuments/fushimi-inari.jpg" },
  { id: "kinkaku-ji", name: "Kinkaku-ji (The Golden Pavilion)", country: "Japan", region: "Asia", image: "/monuments/kinkaku-ji.jpg" },
  { id: "osaka-castle", name: "Osaka Castle", country: "Japan", region: "Asia", image: "/monuments/osaka-castle.jpg" },
  { id: "mount-bromo", name: "Mount Bromo", country: "Indonesia", region: "Asia", image: "/monuments/mount-bromo.jpg" },
  { id: "komodo-national-park", name: "Komodo National Park", country: "Indonesia", region: "Asia", image: "/monuments/komodo-national-park.jpg" },
  { id: "ha-long-bay", name: "Ha Long Bay", country: "Vietnam", region: "Asia", image: "/monuments/ha-long-bay.jpg" },
  { id: "hoi-an", name: "Hoi An Ancient Town", country: "Vietnam", region: "Asia", image: "/monuments/hoi-an.jpg" },
  { id: "wat-arun", name: "Wat Arun", country: "Thailand", region: "Asia", image: "/monuments/wat-arun.jpg" },
  { id: "grand-palace-bangkok", name: "The Grand Palace", country: "Thailand", region: "Asia", image: "/monuments/grand-palace-bangkok.jpg" },
  { id: "gyeongbokgung", name: "Gyeongbokgung Palace", country: "South Korea", region: "Asia", image: "/monuments/gyeongbokgung.jpg" },
  { id: "n-seoul-tower", name: "N Seoul Tower", country: "South Korea", region: "Asia", image: "/monuments/n-seoul-tower.jpg" },
  { id: "marina-bay-sands", name: "Marina Bay Sands", country: "Singapore", region: "Asia", image: "/monuments/marina-bay-sands.jpg" },
  { id: "gardens-by-the-bay", name: "Gardens by the Bay", country: "Singapore", region: "Asia", image: "/monuments/gardens-by-the-bay.jpg" },
  { id: "petronas-towers", name: "The Petronas Towers", country: "Malaysia", region: "Asia", image: "/monuments/petronas-towers.jpg" },
  { id: "chocolate-hills", name: "The Chocolate Hills", country: "Philippines", region: "Asia", image: "/monuments/chocolate-hills.jpg" },
  { id: "jaisalmer-fort", name: "Jaisalmer Fort", country: "India", region: "Asia", image: "/monuments/jaisalmer-fort.jpg" },
  { id: "hawa-mahal", name: "Hawa Mahal", country: "India", region: "Asia", image: "/monuments/hawa-mahal.jpg" },
  { id: "amber-fort", name: "Amber Fort", country: "India", region: "Asia", image: "/monuments/amber-fort.jpg" },
  { id: "varanasi-ghats", name: "The Ghats of Varanasi", country: "India", region: "Asia", image: "/monuments/varanasi-ghats.jpg" },
  { id: "everest-base-camp", name: "Mount Everest", country: "Nepal", region: "Asia", image: "/monuments/everest-base-camp.jpg" },

  // Middle East
  { id: "petra", name: "Petra", country: "Jordan", region: "Middle East", image: "/monuments/petra.jpg" },
  { id: "dome-of-the-rock", name: "Dome of the Rock", country: "Jerusalem", region: "Middle East", image: "/monuments/dome-of-the-rock.jpg" },
  { id: "burj-khalifa", name: "Burj Khalifa", country: "United Arab Emirates", region: "Middle East", image: "/monuments/burj-khalifa.jpg" },
  { id: "sheikh-zayed-mosque", name: "Sheikh Zayed Mosque", country: "United Arab Emirates", region: "Middle East", image: "/monuments/sheikh-zayed-mosque.jpg" },
  { id: "persepolis", name: "Persepolis", country: "Iran", region: "Middle East", image: "/monuments/persepolis.jpg" },
  { id: "blue-mosque", name: "The Blue Mosque", country: "Turkey", region: "Middle East", image: "/monuments/blue-mosque.jpg" },
  { id: "hagia-sophia", name: "Hagia Sophia", country: "Turkey", region: "Middle East", image: "/monuments/hagia-sophia.jpg" },
  { id: "cappadocia", name: "Cappadocia", country: "Turkey", region: "Middle East", image: "/monuments/cappadocia.jpg" },
  { id: "pamukkale", name: "Pamukkale", country: "Turkey", region: "Middle East", image: "/monuments/pamukkale.jpg" },
  { id: "western-wall", name: "The Western Wall", country: "Jerusalem", region: "Middle East", image: "/monuments/western-wall.jpg" },
  { id: "palmyra", name: "Palmyra", country: "Syria", region: "Middle East", image: "/monuments/palmyra.jpg" },
  { id: "palm-jumeirah", name: "Palm Jumeirah", country: "United Arab Emirates", region: "Middle East", image: "/monuments/palm-jumeirah.jpg" },
  { id: "dubai-frame", name: "The Dubai Frame", country: "United Arab Emirates", region: "Middle East", image: "/monuments/dubai-frame.jpg" },
  { id: "wadi-rum", name: "Wadi Rum", country: "Jordan", region: "Middle East", image: "/monuments/wadi-rum.jpg" },
  { id: "jeita-grotto", name: "Jeita Grotto", country: "Lebanon", region: "Middle East", image: "/monuments/jeita-grotto.jpg" },
  { id: "baalbek", name: "Baalbek", country: "Lebanon", region: "Middle East", image: "/monuments/baalbek.jpg" },
  { id: "museum-of-islamic-art-doha", name: "The Museum of Islamic Art", country: "Qatar", region: "Middle East", image: "/monuments/museum-of-islamic-art-doha.jpg" },

  // Europe
  { id: "eiffel-tower", name: "The Eiffel Tower", country: "France", region: "Europe", image: "/monuments/eiffel-tower.jpg" },
  { id: "colosseum", name: "The Colosseum", country: "Italy", region: "Europe", image: "/monuments/colosseum.jpg" },
  { id: "big-ben", name: "Big Ben", country: "United Kingdom", region: "Europe", image: "/monuments/big-ben.jpg" },
  { id: "neuschwanstein", name: "Neuschwanstein Castle", country: "Germany", region: "Europe", image: "/monuments/neuschwanstein.jpg" },
  { id: "sagrada-familia", name: "The Sagrada Familia", country: "Spain", region: "Europe", image: "/monuments/sagrada-familia.jpg" },
  { id: "acropolis", name: "The Acropolis", country: "Greece", region: "Europe", image: "/monuments/acropolis.jpg" },
  { id: "stonehenge", name: "Stonehenge", country: "United Kingdom", region: "Europe", image: "/monuments/stonehenge.jpg" },
  { id: "pisa-tower", name: "The Leaning Tower of Pisa", country: "Italy", region: "Europe", image: "/monuments/pisa-tower.jpg" },
  { id: "arc-de-triomphe", name: "The Arc de Triomphe", country: "France", region: "Europe", image: "/monuments/arc-de-triomphe.jpg" },
  { id: "st-basils", name: "St. Basil's Cathedral", country: "Russia", region: "Europe", image: "/monuments/st-basils.jpg" },
  { id: "louvre", name: "The Louvre", country: "France", region: "Europe", image: "/monuments/louvre.jpg" },
  { id: "notre-dame", name: "Notre-Dame Cathedral", country: "France", region: "Europe", image: "/monuments/notre-dame.jpg" },
  { id: "mont-saint-michel", name: "Mont Saint-Michel", country: "France", region: "Europe", image: "/monuments/mont-saint-michel.jpg" },
  { id: "versailles", name: "The Palace of Versailles", country: "France", region: "Europe", image: "/monuments/versailles.jpg" },
  { id: "brandenburg-gate", name: "The Brandenburg Gate", country: "Germany", region: "Europe", image: "/monuments/brandenburg-gate.jpg" },
  { id: "cologne-cathedral", name: "Cologne Cathedral", country: "Germany", region: "Europe", image: "/monuments/cologne-cathedral.jpg" },
  { id: "berlin-wall", name: "The East Side Gallery", country: "Germany", region: "Europe", image: "/monuments/berlin-wall.jpg" },
  { id: "venice-canals", name: "The Grand Canal", country: "Italy", region: "Europe", image: "/monuments/venice-canals.jpg" },
  { id: "trevi-fountain", name: "The Trevi Fountain", country: "Italy", region: "Europe", image: "/monuments/trevi-fountain.jpg" },
  { id: "milan-cathedral", name: "Milan Cathedral", country: "Italy", region: "Europe", image: "/monuments/milan-cathedral.jpg" },
  { id: "st-peters-basilica", name: "St. Peter's Basilica", country: "Vatican City", region: "Europe", image: "/monuments/st-peters-basilica.jpg" },
  { id: "amalfi-coast", name: "The Amalfi Coast", country: "Italy", region: "Europe", image: "/monuments/amalfi-coast.jpg" },
  { id: "cinque-terre", name: "Cinque Terre", country: "Italy", region: "Europe", image: "/monuments/cinque-terre.jpg" },
  { id: "alhambra", name: "The Alhambra", country: "Spain", region: "Europe", image: "/monuments/alhambra.jpg" },
  { id: "park-guell", name: "Park Güell", country: "Spain", region: "Europe", image: "/monuments/park-guell.jpg" },
  { id: "santorini", name: "Santorini", country: "Greece", region: "Europe", image: "/monuments/santorini.jpg" },
  { id: "meteora", name: "Meteora", country: "Greece", region: "Europe", image: "/monuments/meteora.jpg" },
  { id: "buckingham-palace", name: "Buckingham Palace", country: "United Kingdom", region: "Europe", image: "/monuments/buckingham-palace.jpg" },
  { id: "tower-bridge", name: "Tower Bridge", country: "United Kingdom", region: "Europe", image: "/monuments/tower-bridge.jpg" },
  { id: "tower-of-london", name: "The Tower of London", country: "United Kingdom", region: "Europe", image: "/monuments/tower-of-london.jpg" },
  { id: "edinburgh-castle", name: "Edinburgh Castle", country: "United Kingdom", region: "Europe", image: "/monuments/edinburgh-castle.jpg" },
  { id: "giants-causeway", name: "The Giant's Causeway", country: "United Kingdom", region: "Europe", image: "/monuments/giants-causeway.jpg" },
  { id: "cliffs-of-moher", name: "The Cliffs of Moher", country: "Ireland", region: "Europe", image: "/monuments/cliffs-of-moher.jpg" },
  { id: "kinderdijk-windmills", name: "The Windmills of Kinderdijk", country: "Netherlands", region: "Europe", image: "/monuments/kinderdijk-windmills.jpg" },
  { id: "amsterdam-canals", name: "The Canals of Amsterdam", country: "Netherlands", region: "Europe", image: "/monuments/amsterdam-canals.jpg" },
  { id: "charles-bridge", name: "Charles Bridge", country: "Czech Republic", region: "Europe", image: "/monuments/charles-bridge.jpg" },
  { id: "prague-castle", name: "Prague Castle", country: "Czech Republic", region: "Europe", image: "/monuments/prague-castle.jpg" },
  { id: "schonbrunn-palace", name: "Schönbrunn Palace", country: "Austria", region: "Europe", image: "/monuments/schonbrunn-palace.jpg" },
  { id: "hallstatt", name: "Hallstatt", country: "Austria", region: "Europe", image: "/monuments/hallstatt.jpg" },
  { id: "matterhorn", name: "The Matterhorn", country: "Switzerland", region: "Europe", image: "/monuments/matterhorn.jpg" },
  { id: "plitvice-lakes", name: "Plitvice Lakes", country: "Croatia", region: "Europe", image: "/monuments/plitvice-lakes.jpg" },
  { id: "dubrovnik-old-town", name: "Dubrovnik Old Town", country: "Croatia", region: "Europe", image: "/monuments/dubrovnik-old-town.jpg" },
  { id: "sintra-pena-palace", name: "Pena Palace", country: "Portugal", region: "Europe", image: "/monuments/sintra-pena-palace.jpg" },
  { id: "belem-tower", name: "Belém Tower", country: "Portugal", region: "Europe", image: "/monuments/belem-tower.jpg" },
  { id: "moscow-kremlin", name: "The Moscow Kremlin", country: "Russia", region: "Europe", image: "/monuments/moscow-kremlin.jpg" },
  { id: "lake-bled", name: "Lake Bled", country: "Slovenia", region: "Europe", image: "/monuments/lake-bled.jpg" },

  // Africa
  { id: "pyramids-giza", name: "The Pyramids of Giza", country: "Egypt", region: "Africa", image: "/monuments/pyramids-giza.jpg" },
  { id: "sphinx", name: "The Great Sphinx", country: "Egypt", region: "Africa", image: "/monuments/sphinx.jpg" },
  { id: "table-mountain", name: "Table Mountain", country: "South Africa", region: "Africa", image: "/monuments/table-mountain.jpg" },
  { id: "victoria-falls", name: "Victoria Falls", country: "Zambia", region: "Africa", image: "/monuments/victoria-falls.jpg" },
  { id: "djenne-mosque", name: "The Great Mosque of Djenné", country: "Mali", region: "Africa", image: "/monuments/djenne-mosque.jpg" },
  { id: "lalibela", name: "The Rock Churches of Lalibela", country: "Ethiopia", region: "Africa", image: "/monuments/lalibela.jpg" },
  { id: "karnak-temple", name: "The Karnak Temple", country: "Egypt", region: "Africa", image: "/monuments/karnak-temple.jpg" },
  { id: "valley-of-the-kings", name: "The Valley of the Kings", country: "Egypt", region: "Africa", image: "/monuments/valley-of-the-kings.jpg" },
  { id: "abu-simbel", name: "The Abu Simbel Temples", country: "Egypt", region: "Africa", image: "/monuments/abu-simbel.jpg" },
  { id: "serengeti", name: "The Serengeti", country: "Tanzania", region: "Africa", image: "/monuments/serengeti.jpg" },
  { id: "ngorongoro-crater", name: "The Ngorongoro Crater", country: "Tanzania", region: "Africa", image: "/monuments/ngorongoro-crater.jpg" },
  { id: "mount-kilimanjaro", name: "Mount Kilimanjaro", country: "Tanzania", region: "Africa", image: "/monuments/mount-kilimanjaro.jpg" },
  { id: "maasai-mara", name: "The Maasai Mara", country: "Kenya", region: "Africa", image: "/monuments/maasai-mara.jpg" },
  { id: "sahara-desert", name: "The Sahara Desert", country: "Morocco", region: "Africa", image: "/monuments/sahara-desert.jpg" },
  { id: "chefchaouen", name: "Chefchaouen", country: "Morocco", region: "Africa", image: "/monuments/chefchaouen.jpg" },
  { id: "jemaa-el-fnaa", name: "Jemaa el-Fnaa", country: "Morocco", region: "Africa", image: "/monuments/jemaa-el-fnaa.jpg" },
  { id: "hassan-ii-mosque", name: "The Hassan II Mosque", country: "Morocco", region: "Africa", image: "/monuments/hassan-ii-mosque.jpg" },
  { id: "cape-of-good-hope", name: "The Cape of Good Hope", country: "South Africa", region: "Africa", image: "/monuments/cape-of-good-hope.jpg" },
  { id: "robben-island", name: "Robben Island", country: "South Africa", region: "Africa", image: "/monuments/robben-island.jpg" },
  { id: "okavango-delta", name: "The Okavango Delta", country: "Botswana", region: "Africa", image: "/monuments/okavango-delta.jpg" },
  { id: "zanzibar-stone-town", name: "Stone Town", country: "Tanzania", region: "Africa", image: "/monuments/zanzibar-stone-town.jpg" },
  { id: "namib-desert", name: "The Namib Desert", country: "Namibia", region: "Africa", image: "/monuments/namib-desert.jpg" },

  // Americas
  { id: "statue-of-liberty", name: "The Statue of Liberty", country: "United States", region: "Americas", image: "/monuments/statue-of-liberty.jpg" },
  { id: "christ-redeemer", name: "Christ the Redeemer", country: "Brazil", region: "Americas", image: "/monuments/christ-redeemer.jpg" },
  { id: "machu-picchu", name: "Machu Picchu", country: "Peru", region: "Americas", image: "/monuments/machu-picchu.jpg" },
  { id: "chichen-itza", name: "Chichen Itza", country: "Mexico", region: "Americas", image: "/monuments/chichen-itza.jpg" },
  { id: "golden-gate", name: "The Golden Gate Bridge", country: "United States", region: "Americas", image: "/monuments/golden-gate.jpg" },
  { id: "gateway-arch", name: "The Gateway Arch", country: "United States", region: "Americas", image: "/monuments/gateway-arch.jpg" },
  { id: "cn-tower", name: "The CN Tower", country: "Canada", region: "Americas", image: "/monuments/cn-tower.jpg" },
  { id: "niagara-falls", name: "Niagara Falls", country: "Canada", region: "Americas", image: "/monuments/niagara-falls.jpg" },
  { id: "moai", name: "The Moai of Easter Island", country: "Chile", region: "Americas", image: "/monuments/moai.jpg" },
  { id: "teotihuacan", name: "Teotihuacan", country: "Mexico", region: "Americas", image: "/monuments/teotihuacan.jpg" },
  { id: "grand-canyon", name: "The Grand Canyon", country: "United States", region: "Americas", image: "/monuments/grand-canyon.jpg" },
  { id: "yellowstone", name: "Yellowstone National Park", country: "United States", region: "Americas", image: "/monuments/yellowstone.jpg" },
  { id: "mount-rushmore", name: "Mount Rushmore", country: "United States", region: "Americas", image: "/monuments/mount-rushmore.jpg" },
  { id: "hollywood-sign", name: "The Hollywood Sign", country: "United States", region: "Americas", image: "/monuments/hollywood-sign.jpg" },
  { id: "times-square", name: "Times Square", country: "United States", region: "Americas", image: "/monuments/times-square.jpg" },
  { id: "las-vegas-strip", name: "The Las Vegas Strip", country: "United States", region: "Americas", image: "/monuments/las-vegas-strip.jpg" },
  { id: "white-house", name: "The White House", country: "United States", region: "Americas", image: "/monuments/white-house.jpg" },
  { id: "lincoln-memorial", name: "The Lincoln Memorial", country: "United States", region: "Americas", image: "/monuments/lincoln-memorial.jpg" },
  { id: "empire-state-building", name: "The Empire State Building", country: "United States", region: "Americas", image: "/monuments/empire-state-building.jpg" },
  { id: "brooklyn-bridge", name: "The Brooklyn Bridge", country: "United States", region: "Americas", image: "/monuments/brooklyn-bridge.jpg" },
  { id: "hoover-dam", name: "The Hoover Dam", country: "United States", region: "Americas", image: "/monuments/hoover-dam.jpg" },
  { id: "yosemite", name: "Yosemite National Park", country: "United States", region: "Americas", image: "/monuments/yosemite.jpg" },
  { id: "antelope-canyon", name: "Antelope Canyon", country: "United States", region: "Americas", image: "/monuments/antelope-canyon.jpg" },
  { id: "metropolitan-museum", name: "The Metropolitan Museum of Art", country: "United States", region: "Americas", image: "/monuments/metropolitan-museum.jpg" },
  { id: "space-needle", name: "The Space Needle", country: "United States", region: "Americas", image: "/monuments/space-needle.jpg" },
  { id: "alcatraz", name: "Alcatraz Island", country: "United States", region: "Americas", image: "/monuments/alcatraz.jpg" },
  { id: "washington-monument", name: "The Washington Monument", country: "United States", region: "Americas", image: "/monuments/washington-monument.jpg" },
  { id: "one-world-trade-center", name: "One World Trade Center", country: "United States", region: "Americas", image: "/monuments/one-world-trade-center.jpg" },
  { id: "chicago-bean", name: "Cloud Gate", country: "United States", region: "Americas", image: "/monuments/chicago-bean.jpg" },
  { id: "french-quarter-new-orleans", name: "The French Quarter", country: "United States", region: "Americas", image: "/monuments/french-quarter-new-orleans.jpg" },
  { id: "banff-national-park", name: "Banff National Park", country: "Canada", region: "Americas", image: "/monuments/banff-national-park.jpg" },
  { id: "lake-louise", name: "Lake Louise", country: "Canada", region: "Americas", image: "/monuments/lake-louise.jpg" },
  { id: "tulum", name: "Tulum", country: "Mexico", region: "Americas", image: "/monuments/tulum.jpg" },
  { id: "iguazu-falls", name: "Iguazu Falls", country: "Brazil", region: "Americas", image: "/monuments/iguazu-falls.jpg" },
  { id: "copacabana-beach", name: "Copacabana Beach", country: "Brazil", region: "Americas", image: "/monuments/copacabana-beach.jpg" },
  { id: "amazon-rainforest", name: "The Amazon Rainforest", country: "Brazil", region: "Americas", image: "/monuments/amazon-rainforest.jpg" },
  { id: "salar-de-uyuni", name: "Salar de Uyuni", country: "Bolivia", region: "Americas", image: "/monuments/salar-de-uyuni.jpg" },
  { id: "galapagos-islands", name: "The Galápagos Islands", country: "Ecuador", region: "Americas", image: "/monuments/galapagos-islands.jpg" },
  { id: "cartagena-old-town", name: "Cartagena's Old Town", country: "Colombia", region: "Americas", image: "/monuments/cartagena-old-town.jpg" },
  { id: "torres-del-paine", name: "Torres del Paine", country: "Chile", region: "Americas", image: "/monuments/torres-del-paine.jpg" },
  { id: "perito-moreno-glacier", name: "The Perito Moreno Glacier", country: "Argentina", region: "Americas", image: "/monuments/perito-moreno-glacier.jpg" },
  { id: "obelisco-buenos-aires", name: "The Obelisco de Buenos Aires", country: "Argentina", region: "Americas", image: "/monuments/obelisco-buenos-aires.jpg" },
  { id: "havana-old-town", name: "Old Havana", country: "Cuba", region: "Americas", image: "/monuments/havana-old-town.jpg" },
  { id: "panama-canal", name: "The Panama Canal", country: "Panama", region: "Americas", image: "/monuments/panama-canal.jpg" },

  // Oceania
  { id: "sydney-opera-house", name: "The Sydney Opera House", country: "Australia", region: "Oceania", image: "/monuments/sydney-opera-house.jpg" },
  { id: "sydney-harbour-bridge", name: "The Sydney Harbour Bridge", country: "Australia", region: "Oceania", image: "/monuments/sydney-harbour-bridge.jpg" },
  { id: "uluru", name: "Uluru", country: "Australia", region: "Oceania", image: "/monuments/uluru.jpg" },
  { id: "sky-tower", name: "The Sky Tower", country: "New Zealand", region: "Oceania", image: "/monuments/sky-tower.jpg" },
  { id: "great-barrier-reef", name: "The Great Barrier Reef", country: "Australia", region: "Oceania", image: "/monuments/great-barrier-reef.jpg" },
  { id: "bondi-beach", name: "Bondi Beach", country: "Australia", region: "Oceania", image: "/monuments/bondi-beach.jpg" },
  { id: "twelve-apostles", name: "The Twelve Apostles", country: "Australia", region: "Oceania", image: "/monuments/twelve-apostles.jpg" },
  { id: "kata-tjuta", name: "Kata Tjuta", country: "Australia", region: "Oceania", image: "/monuments/kata-tjuta.jpg" },
  { id: "daintree-rainforest", name: "The Daintree Rainforest", country: "Australia", region: "Oceania", image: "/monuments/daintree-rainforest.jpg" },
  { id: "milford-sound", name: "Milford Sound", country: "New Zealand", region: "Oceania", image: "/monuments/milford-sound.jpg" },
  { id: "tongariro-national-park", name: "Tongariro National Park", country: "New Zealand", region: "Oceania", image: "/monuments/tongariro-national-park.jpg" },
  { id: "waitomo-glowworm-caves", name: "The Waitomo Glowworm Caves", country: "New Zealand", region: "Oceania", image: "/monuments/waitomo-glowworm-caves.jpg" },
  { id: "hobbiton", name: "Hobbiton Movie Set", country: "New Zealand", region: "Oceania", image: "/monuments/hobbiton.jpg" },
  { id: "bora-bora", name: "Bora Bora", country: "French Polynesia", region: "Oceania", image: "/monuments/bora-bora.jpg" },
  // --- 500-landmark expansion ---
  // Asia (expansion)
  { id: "golden-temple", name: "The Golden Temple", country: "India", region: "Asia", image: "/monuments/golden-temple.jpg" },
  { id: "red-fort", name: "The Red Fort", country: "India", region: "Asia", image: "/monuments/red-fort.jpg" },
  { id: "qutub-minar", name: "Qutub Minar", country: "India", region: "Asia", image: "/monuments/qutub-minar.jpg" },
  { id: "gateway-of-india", name: "The Gateway of India", country: "India", region: "Asia", image: "/monuments/gateway-of-india.jpg" },
  { id: "lotus-temple", name: "The Lotus Temple", country: "India", region: "Asia", image: "/monuments/lotus-temple.jpg" },
  { id: "humayuns-tomb", name: "Humayun's Tomb", country: "India", region: "Asia", image: "/monuments/humayuns-tomb.jpg" },
  { id: "mysore-palace", name: "Mysore Palace", country: "India", region: "Asia", image: "/monuments/mysore-palace.jpg" },
  { id: "khajuraho", name: "Khajuraho Temples", country: "India", region: "Asia", image: "/monuments/khajuraho.jpg" },
  { id: "ajanta-caves", name: "The Ajanta Caves", country: "India", region: "Asia", image: "/monuments/ajanta-caves.jpg" },
  { id: "mehrangarh-fort", name: "Mehrangarh Fort", country: "India", region: "Asia", image: "/monuments/mehrangarh-fort.jpg" },
  { id: "udaipur-city-palace", name: "The City Palace of Udaipur", country: "India", region: "Asia", image: "/monuments/udaipur-city-palace.jpg" },
  { id: "golden-rock-tirupati", name: "The Tirupati Temple", country: "India", region: "Asia", image: "/monuments/golden-rock-tirupati.jpg" },
  { id: "dal-lake", name: "Dal Lake", country: "India", region: "Asia", image: "/monuments/dal-lake.jpg" },
  { id: "valley-of-flowers", name: "The Valley of Flowers", country: "India", region: "Asia", image: "/monuments/valley-of-flowers.jpg" },
  { id: "ranthambore", name: "Ranthambore National Park", country: "India", region: "Asia", image: "/monuments/ranthambore.jpg" },
  { id: "jim-corbett", name: "Jim Corbett National Park", country: "India", region: "Asia", image: "/monuments/jim-corbett.jpg" },
  { id: "kaziranga", name: "Kaziranga National Park", country: "India", region: "Asia", image: "/monuments/kaziranga.jpg" },
  { id: "sundarbans", name: "The Sundarbans", country: "India", region: "Asia", image: "/monuments/sundarbans.jpg" },
  { id: "gir-forest", name: "Gir National Park", country: "India", region: "Asia", image: "/monuments/gir-forest.jpg" },
  { id: "rann-of-kutch", name: "The Rann of Kutch", country: "India", region: "Asia", image: "/monuments/rann-of-kutch.jpg" },
  { id: "munnar-hills", name: "The Munnar Hills", country: "India", region: "Asia", image: "/monuments/munnar-hills.jpg" },
  { id: "hampi", name: "Hampi", country: "India", region: "Asia", image: "/monuments/hampi.jpg" },
  { id: "gateway-arch-india-vsakshi", name: "India Gate", country: "India", region: "Asia", image: "/monuments/gateway-arch-india-vsakshi.jpg" },
  { id: "cellular-jail", name: "The Cellular Jail", country: "India", region: "Asia", image: "/monuments/cellular-jail.jpg" },
  { id: "living-root-bridges", name: "The Living Root Bridges", country: "India", region: "Asia", image: "/monuments/living-root-bridges.jpg" },
  { id: "leh-palace", name: "Leh Palace", country: "India", region: "Asia", image: "/monuments/leh-palace.jpg" },
  { id: "pangong-lake", name: "Pangong Lake", country: "India", region: "Asia", image: "/monuments/pangong-lake.jpg" },
  { id: "golconda-fort", name: "Golconda Fort", country: "India", region: "Asia", image: "/monuments/golconda-fort.jpg" },
  { id: "elephanta-caves", name: "The Elephanta Caves", country: "India", region: "Asia", image: "/monuments/elephanta-caves.jpg" },
  { id: "sanchi-stupa", name: "The Great Stupa at Sanchi", country: "India", region: "Asia", image: "/monuments/sanchi-stupa.jpg" },
  { id: "brihadeeswarar-temple", name: "The Brihadeeswarar Temple", country: "India", region: "Asia", image: "/monuments/brihadeeswarar-temple.jpg" },
  { id: "marina-beach", name: "Marina Beach", country: "India", region: "Asia", image: "/monuments/marina-beach.jpg" },
  { id: "nubra-valley", name: "The Nubra Valley", country: "India", region: "Asia", image: "/monuments/nubra-valley.jpg" },
  { id: "kailash-temple", name: "The Kailasa Temple", country: "India", region: "Asia", image: "/monuments/kailash-temple.jpg" },
  { id: "jantar-mantar", name: "Jantar Mantar", country: "India", region: "Asia", image: "/monuments/jantar-mantar.jpg" },
  { id: "lakshadweep", name: "Lakshadweep Islands", country: "India", region: "Asia", image: "/monuments/lakshadweep.jpg" },
  { id: "andaman-beaches", name: "Radhanagar Beach", country: "India", region: "Asia", image: "/monuments/andaman-beaches.jpg" },
  { id: "shimla-hills", name: "Shimla", country: "India", region: "Asia", image: "/monuments/shimla-hills.jpg" },
  { id: "darjeeling-tea-gardens", name: "The Darjeeling Tea Gardens", country: "India", region: "Asia", image: "/monuments/darjeeling-tea-gardens.jpg" },
  { id: "kanchenjunga", name: "Kanchenjunga", country: "India", region: "Asia", image: "/monuments/kanchenjunga.jpg" },
  { id: "lion-rock-sigiriya", name: "Sigiriya", country: "Sri Lanka", region: "Asia", image: "/monuments/lion-rock-sigiriya.jpg" },
  { id: "temple-of-the-tooth", name: "The Temple of the Sacred Tooth Relic", country: "Sri Lanka", region: "Asia", image: "/monuments/temple-of-the-tooth.jpg" },
  { id: "galle-fort", name: "Galle Fort", country: "Sri Lanka", region: "Asia", image: "/monuments/galle-fort.jpg" },
  { id: "pokhara-nepal", name: "Phewa Lake", country: "Nepal", region: "Asia", image: "/monuments/pokhara-nepal.jpg" },
  { id: "boudhanath", name: "Boudhanath Stupa", country: "Nepal", region: "Asia", image: "/monuments/boudhanath.jpg" },
  { id: "sundarbans-bangladesh", name: "The Sundarbans (Bangladesh side)", country: "Bangladesh", region: "Asia", image: "/monuments/sundarbans-bangladesh.jpg" },
  { id: "badshahi-mosque", name: "The Badshahi Mosque", country: "Pakistan", region: "Asia", image: "/monuments/badshahi-mosque.jpg" },
  { id: "lahore-fort", name: "Lahore Fort", country: "Pakistan", region: "Asia", image: "/monuments/lahore-fort.jpg" },
  { id: "faisal-mosque", name: "The Faisal Mosque", country: "Pakistan", region: "Asia", image: "/monuments/faisal-mosque.jpg" },
  { id: "k2", name: "K2", country: "Pakistan", region: "Asia", image: "/monuments/k2.jpg" },
  { id: "registan", name: "The Registan", country: "Uzbekistan", region: "Asia", image: "/monuments/registan.jpg" },
  { id: "shahi-zinda", name: "Shah-i-Zinda", country: "Uzbekistan", region: "Asia", image: "/monuments/shahi-zinda.jpg" },
  { id: "charyn-canyon", name: "Charyn Canyon", country: "Kazakhstan", region: "Asia", image: "/monuments/charyn-canyon.jpg" },
  { id: "darvaza-crater", name: "The Darvaza Gas Crater", country: "Turkmenistan", region: "Asia", image: "/monuments/darvaza-crater.jpg" },
  { id: "son-doong-cave", name: "Sơn Đoòng Cave", country: "Vietnam", region: "Asia", image: "/monuments/son-doong-cave.jpg" },
  { id: "phi-phi-islands", name: "The Phi Phi Islands", country: "Thailand", region: "Asia", image: "/monuments/phi-phi-islands.jpg" },
  { id: "ayutthaya", name: "Ayutthaya Historical Park", country: "Thailand", region: "Asia", image: "/monuments/ayutthaya.jpg" },
  { id: "railay-beach", name: "Railay Beach", country: "Thailand", region: "Asia", image: "/monuments/railay-beach.jpg" },
  { id: "kuang-si-falls", name: "Kuang Si Falls", country: "Laos", region: "Asia", image: "/monuments/kuang-si-falls.jpg" },
  { id: "plain-of-jars", name: "The Plain of Jars", country: "Laos", region: "Asia", image: "/monuments/plain-of-jars.jpg" },
  { id: "bagan", name: "Bagan", country: "Myanmar", region: "Asia", image: "/monuments/bagan.jpg" },
  { id: "inle-lake", name: "Inle Lake", country: "Myanmar", region: "Asia", image: "/monuments/inle-lake.jpg" },
  { id: "preah-vihear", name: "Preah Vihear Temple", country: "Cambodia", region: "Asia", image: "/monuments/preah-vihear.jpg" },
  { id: "tonle-sap", name: "Tonlé Sap", country: "Cambodia", region: "Asia", image: "/monuments/tonle-sap.jpg" },
  { id: "rice-terraces-banaue", name: "The Banaue Rice Terraces", country: "Philippines", region: "Asia", image: "/monuments/rice-terraces-banaue.jpg" },
  { id: "palawan-underground-river", name: "The Puerto Princesa Underground River", country: "Philippines", region: "Asia", image: "/monuments/palawan-underground-river.jpg" },
  { id: "boracay", name: "Boracay", country: "Philippines", region: "Asia", image: "/monuments/boracay.jpg" },
  { id: "mount-mayon", name: "Mount Mayon", country: "Philippines", region: "Asia", image: "/monuments/mount-mayon.jpg" },
  { id: "batu-caves", name: "Batu Caves", country: "Malaysia", region: "Asia", image: "/monuments/batu-caves.jpg" },
  { id: "mount-kinabalu", name: "Mount Kinabalu", country: "Malaysia", region: "Asia", image: "/monuments/mount-kinabalu.jpg" },
  { id: "langkawi", name: "Langkawi", country: "Malaysia", region: "Asia", image: "/monuments/langkawi.jpg" },
  { id: "tanah-lot", name: "Tanah Lot", country: "Indonesia", region: "Asia", image: "/monuments/tanah-lot.jpg" },
  { id: "mount-bromo-indonesia", name: "Kawah Ijen", country: "Indonesia", region: "Asia", image: "/monuments/mount-bromo-indonesia.jpg" },
  { id: "raja-ampat", name: "Raja Ampat Islands", country: "Indonesia", region: "Asia", image: "/monuments/raja-ampat.jpg" },
  { id: "prambanan", name: "Prambanan", country: "Indonesia", region: "Asia", image: "/monuments/prambanan.jpg" },
  { id: "jeju-island", name: "Jeju Island", country: "South Korea", region: "Asia", image: "/monuments/jeju-island.jpg" },
  { id: "bukchon-hanok-village", name: "Bukchon Hanok Village", country: "South Korea", region: "Asia", image: "/monuments/bukchon-hanok-village.jpg" },
  { id: "changdeokgung", name: "Changdeokgung Palace", country: "South Korea", region: "Asia", image: "/monuments/changdeokgung.jpg" },
  { id: "mount-fansipan", name: "Fansipan", country: "Vietnam", region: "Asia", image: "/monuments/mount-fansipan.jpg" },
  { id: "arashiyama-bamboo-grove", name: "The Arashiyama Bamboo Grove", country: "Japan", region: "Asia", image: "/monuments/arashiyama-bamboo-grove.jpg" },
  { id: "nara-park", name: "Nara Park", country: "Japan", region: "Asia", image: "/monuments/nara-park.jpg" },
  { id: "itsukushima-shrine", name: "Itsukushima Shrine", country: "Japan", region: "Asia", image: "/monuments/itsukushima-shrine.jpg" },
  { id: "mount-koya", name: "Mount Kōya", country: "Japan", region: "Asia", image: "/monuments/mount-koya.jpg" },
  { id: "shirakawa-go", name: "Shirakawa-gō", country: "Japan", region: "Asia", image: "/monuments/shirakawa-go.jpg" },
  { id: "okinawa-beaches", name: "The Beaches of Okinawa", country: "Japan", region: "Asia", image: "/monuments/okinawa-beaches.jpg" },
  { id: "jiuzhaigou", name: "Jiuzhaigou Valley", country: "China", region: "Asia", image: "/monuments/jiuzhaigou.jpg" },
  { id: "guilin-hills", name: "The Guilin Hills", country: "China", region: "Asia", image: "/monuments/guilin-hills.jpg" },
  { id: "yellow-mountain", name: "Mount Huangshan", country: "China", region: "Asia", image: "/monuments/yellow-mountain.jpg" },
  { id: "leshan-giant-buddha", name: "The Leshan Giant Buddha", country: "China", region: "Asia", image: "/monuments/leshan-giant-buddha.jpg" },
  { id: "the-bund", name: "The Bund", country: "China", region: "Asia", image: "/monuments/the-bund.jpg" },
  { id: "mongolia-gobi-desert", name: "The Gobi Desert", country: "Mongolia", region: "Asia", image: "/monuments/mongolia-gobi-desert.jpg" },
  { id: "lake-baikal", name: "Lake Baikal", country: "Russia", region: "Asia", image: "/monuments/lake-baikal.jpg" },
  { id: "pamir-highway", name: "The Pamir Highway", country: "Tajikistan", region: "Asia", image: "/monuments/pamir-highway.jpg" },
  { id: "iskanderkul", name: "Lake Iskanderkul", country: "Tajikistan", region: "Asia", image: "/monuments/iskanderkul.jpg" },
  { id: "song-kul", name: "Song-Kul Lake", country: "Kyrgyzstan", region: "Asia", image: "/monuments/song-kul.jpg" },
  { id: "ala-archa", name: "Ala Archa National Park", country: "Kyrgyzstan", region: "Asia", image: "/monuments/ala-archa.jpg" },
  { id: "olkhon-island", name: "Olkhon Island", country: "Russia", region: "Asia", image: "/monuments/olkhon-island.jpg" },
  { id: "kamchatka-volcanoes", name: "The Valley of Geysers", country: "Russia", region: "Asia", image: "/monuments/kamchatka-volcanoes.jpg" },
  { id: "altai-mountains", name: "The Altai Mountains", country: "Russia", region: "Asia", image: "/monuments/altai-mountains.jpg" },
  { id: "taklamakan-desert", name: "The Taklamakan Desert", country: "China", region: "Asia", image: "/monuments/taklamakan-desert.jpg" },
  { id: "mogao-caves", name: "The Mogao Caves", country: "China", region: "Asia", image: "/monuments/mogao-caves.jpg" },
  { id: "three-gorges-dam", name: "The Three Gorges Dam", country: "China", region: "Asia", image: "/monuments/three-gorges-dam.jpg" },
  { id: "potatso-national-park", name: "Pudacuo National Park", country: "China", region: "Asia", image: "/monuments/potatso-national-park.jpg" },
  { id: "mount-emei", name: "Mount Emei", country: "China", region: "Asia", image: "/monuments/mount-emei.jpg" },
  { id: "lijiang-old-town", name: "Lijiang Old Town", country: "China", region: "Asia", image: "/monuments/lijiang-old-town.jpg" },
  { id: "dazu-rock-carvings", name: "The Dazu Rock Carvings", country: "China", region: "Asia", image: "/monuments/dazu-rock-carvings.jpg" },
  { id: "koh-samui", name: "Koh Samui", country: "Thailand", region: "Asia", image: "/monuments/koh-samui.jpg" },
  { id: "khao-sok", name: "Khao Sok National Park", country: "Thailand", region: "Asia", image: "/monuments/khao-sok.jpg" },
  { id: "gunung-mulu", name: "Gunung Mulu National Park", country: "Malaysia", region: "Asia", image: "/monuments/gunung-mulu.jpg" },
  { id: "cameron-highlands", name: "The Cameron Highlands", country: "Malaysia", region: "Asia", image: "/monuments/cameron-highlands.jpg" },
  { id: "nusa-penida", name: "Nusa Penida", country: "Indonesia", region: "Asia", image: "/monuments/nusa-penida.jpg" },
  { id: "mount-rinjani", name: "Mount Rinjani", country: "Indonesia", region: "Asia", image: "/monuments/mount-rinjani.jpg" },
  { id: "lake-toba", name: "Lake Toba", country: "Indonesia", region: "Asia", image: "/monuments/lake-toba.jpg" },
  { id: "palau-rock-islands", name: "The Rock Islands of Palau", country: "Palau", region: "Asia", image: "/monuments/palau-rock-islands.jpg" },
  { id: "sun-moon-lake", name: "Sun Moon Lake", country: "Taiwan", region: "Asia", image: "/monuments/sun-moon-lake.jpg" },
  { id: "taroko-gorge", name: "Taroko Gorge", country: "Taiwan", region: "Asia", image: "/monuments/taroko-gorge.jpg" },
  { id: "seokguram-grotto", name: "Seokguram Grotto", country: "South Korea", region: "Asia", image: "/monuments/seokguram-grotto.jpg" },
  { id: "bulguksa-temple", name: "Bulguksa Temple", country: "South Korea", region: "Asia", image: "/monuments/bulguksa-temple.jpg" },
  { id: "hanoi-old-quarter", name: "Hanoi's Old Quarter", country: "Vietnam", region: "Asia", image: "/monuments/hanoi-old-quarter.jpg" },
  { id: "cu-chi-tunnels", name: "The Củ Chi Tunnels", country: "Vietnam", region: "Asia", image: "/monuments/cu-chi-tunnels.jpg" },
  { id: "flores-island", name: "Flores Island", country: "Indonesia", region: "Asia", image: "/monuments/flores-island.jpg" },
  // Middle East (expansion)
  { id: "masjid-al-haram", name: "The Great Mosque of Mecca", country: "Saudi Arabia", region: "Middle East", image: "/monuments/masjid-al-haram.jpg" },
  { id: "al-masjid-an-nabawi", name: "Al-Masjid an-Nabawi", country: "Saudi Arabia", region: "Middle East", image: "/monuments/al-masjid-an-nabawi.jpg" },
  { id: "al-ula", name: "AlUla", country: "Saudi Arabia", region: "Middle East", image: "/monuments/al-ula.jpg" },
  { id: "jeddah-corniche", name: "The Jeddah Corniche", country: "Saudi Arabia", region: "Middle East", image: "/monuments/jeddah-corniche.jpg" },
  { id: "museum-of-the-future", name: "The Museum of the Future", country: "United Arab Emirates", region: "Middle East", image: "/monuments/museum-of-the-future.jpg" },
  { id: "dubai-marina", name: "Dubai Marina", country: "United Arab Emirates", region: "Middle East", image: "/monuments/dubai-marina.jpg" },
  { id: "al-fahidi-fort", name: "Al Fahidi Fort", country: "United Arab Emirates", region: "Middle East", image: "/monuments/al-fahidi-fort.jpg" },
  { id: "liwa-desert", name: "The Liwa Desert", country: "United Arab Emirates", region: "Middle East", image: "/monuments/liwa-desert.jpg" },
  { id: "jebel-jais", name: "Jebel Jais", country: "United Arab Emirates", region: "Middle East", image: "/monuments/jebel-jais.jpg" },
  { id: "souq-waqif", name: "Souq Waqif", country: "Qatar", region: "Middle East", image: "/monuments/souq-waqif.jpg" },
  { id: "katara-cultural-village", name: "Katara Cultural Village", country: "Qatar", region: "Middle East", image: "/monuments/katara-cultural-village.jpg" },
  { id: "the-pearl-qatar", name: "The Pearl-Qatar", country: "Qatar", region: "Middle East", image: "/monuments/the-pearl-qatar.jpg" },
  { id: "bahrain-fort", name: "Bahrain Fort", country: "Bahrain", region: "Middle East", image: "/monuments/bahrain-fort.jpg" },
  { id: "tree-of-life-bahrain", name: "The Tree of Life", country: "Bahrain", region: "Middle East", image: "/monuments/tree-of-life-bahrain.jpg" },
  { id: "kuwait-towers", name: "The Kuwait Towers", country: "Kuwait", region: "Middle East", image: "/monuments/kuwait-towers.jpg" },
  { id: "masada", name: "Masada", country: "Israel", region: "Middle East", image: "/monuments/masada.jpg" },
  { id: "dead-sea", name: "The Dead Sea", country: "Jordan", region: "Middle East", image: "/monuments/dead-sea.jpg" },
  { id: "sea-of-galilee", name: "The Sea of Galilee", country: "Israel", region: "Middle East", image: "/monuments/sea-of-galilee.jpg" },
  { id: "tel-aviv-beach", name: "Tel Aviv Beach", country: "Israel", region: "Middle East", image: "/monuments/tel-aviv-beach.jpg" },
  { id: "jerash", name: "Jerash", country: "Jordan", region: "Middle East", image: "/monuments/jerash.jpg" },
  { id: "amman-citadel", name: "The Amman Citadel", country: "Jordan", region: "Middle East", image: "/monuments/amman-citadel.jpg" },
  { id: "aqaba-red-sea", name: "Aqaba's Red Sea Coast", country: "Jordan", region: "Middle East", image: "/monuments/aqaba-red-sea.jpg" },
  { id: "göreme-national-park", name: "Göreme National Park", country: "Turkey", region: "Middle East", image: "/monuments/göreme-national-park.jpg" },
  { id: "ephesus", name: "Ephesus", country: "Turkey", region: "Middle East", image: "/monuments/ephesus.jpg" },
  { id: "topkapi-palace", name: "Topkapı Palace", country: "Turkey", region: "Middle East", image: "/monuments/topkapi-palace.jpg" },
  { id: "mount-ararat", name: "Mount Ararat", country: "Turkey", region: "Middle East", image: "/monuments/mount-ararat.jpg" },
  { id: "antalya-old-town", name: "Antalya's Old Town", country: "Turkey", region: "Middle East", image: "/monuments/antalya-old-town.jpg" },
  { id: "garden-of-eden-iraq", name: "The Mesopotamian Marshes", country: "Iraq", region: "Middle East", image: "/monuments/garden-of-eden-iraq.jpg" },
  { id: "ziggurat-of-ur", name: "The Great Ziggurat of Ur", country: "Iraq", region: "Middle East", image: "/monuments/ziggurat-of-ur.jpg" },
  { id: "babylon-ruins", name: "The Ruins of Babylon", country: "Iraq", region: "Middle East", image: "/monuments/babylon-ruins.jpg" },
  { id: "shiraz-nasir-mosque", name: "The Nasir al-Mulk Mosque", country: "Iran", region: "Middle East", image: "/monuments/shiraz-nasir-mosque.jpg" },
  { id: "naqsh-e-jahan-square", name: "Naqsh-e Jahan Square", country: "Iran", region: "Middle East", image: "/monuments/naqsh-e-jahan-square.jpg" },
  { id: "golestan-palace", name: "Golestan Palace", country: "Iran", region: "Middle East", image: "/monuments/golestan-palace.jpg" },
  { id: "lut-desert", name: "The Lut Desert", country: "Iran", region: "Middle East", image: "/monuments/lut-desert.jpg" },
  { id: "cedars-of-god", name: "The Cedars of God", country: "Lebanon", region: "Middle East", image: "/monuments/cedars-of-god.jpg" },
  { id: "byblos", name: "Byblos", country: "Lebanon", region: "Middle East", image: "/monuments/byblos.jpg" },
  { id: "salalah-oman", name: "Salalah", country: "Oman", region: "Middle East", image: "/monuments/salalah-oman.jpg" },
  { id: "nizwa-fort", name: "Nizwa Fort", country: "Oman", region: "Middle East", image: "/monuments/nizwa-fort.jpg" },
  { id: "sultan-qaboos-mosque", name: "The Sultan Qaboos Grand Mosque", country: "Oman", region: "Middle East", image: "/monuments/sultan-qaboos-mosque.jpg" },
  // Europe (expansion)
  { id: "chateau-de-chambord", name: "Château de Chambord", country: "France", region: "Europe", image: "/monuments/chateau-de-chambord.jpg" },
  { id: "chateau-de-chenonceau", name: "Château de Chenonceau", country: "France", region: "Europe", image: "/monuments/chateau-de-chenonceau.jpg" },
  { id: "palace-of-fontainebleau", name: "The Palace of Fontainebleau", country: "France", region: "Europe", image: "/monuments/palace-of-fontainebleau.jpg" },
  { id: "lavender-fields-provence", name: "The Lavender Fields of Provence", country: "France", region: "Europe", image: "/monuments/lavender-fields-provence.jpg" },
  { id: "french-riviera", name: "The French Riviera", country: "France", region: "Europe", image: "/monuments/french-riviera.jpg" },
  { id: "pont-du-gard", name: "The Pont du Gard", country: "France", region: "Europe", image: "/monuments/pont-du-gard.jpg" },
  { id: "carcassonne", name: "The Citadel of Carcassonne", country: "France", region: "Europe", image: "/monuments/carcassonne.jpg" },
  { id: "champs-elysees", name: "The Champs-Élysées", country: "France", region: "Europe", image: "/monuments/champs-elysees.jpg" },
  { id: "sacre-coeur", name: "The Sacré-Cœur Basilica", country: "France", region: "Europe", image: "/monuments/sacre-coeur.jpg" },
  { id: "strasbourg-cathedral", name: "Strasbourg Cathedral", country: "France", region: "Europe", image: "/monuments/strasbourg-cathedral.jpg" },
  { id: "munich-marienplatz", name: "Marienplatz", country: "Germany", region: "Europe", image: "/monuments/munich-marienplatz.jpg" },
  { id: "black-forest", name: "The Black Forest", country: "Germany", region: "Europe", image: "/monuments/black-forest.jpg" },
  { id: "heidelberg-castle", name: "Heidelberg Castle", country: "Germany", region: "Europe", image: "/monuments/heidelberg-castle.jpg" },
  { id: "zugspitze", name: "The Zugspitze", country: "Germany", region: "Europe", image: "/monuments/zugspitze.jpg" },
  { id: "rothenburg", name: "Rothenburg ob der Tauber", country: "Germany", region: "Europe", image: "/monuments/rothenburg.jpg" },
  { id: "hamburg-speicherstadt", name: "Speicherstadt", country: "Germany", region: "Europe", image: "/monuments/hamburg-speicherstadt.jpg" },
  { id: "duomo-florence", name: "The Florence Cathedral", country: "Italy", region: "Europe", image: "/monuments/duomo-florence.jpg" },
  { id: "pompeii", name: "Pompeii", country: "Italy", region: "Europe", image: "/monuments/pompeii.jpg" },
  { id: "mount-vesuvius", name: "Mount Vesuvius", country: "Italy", region: "Europe", image: "/monuments/mount-vesuvius.jpg" },
  { id: "capri-island", name: "Capri", country: "Italy", region: "Europe", image: "/monuments/capri-island.jpg" },
  { id: "dolomites", name: "The Dolomites", country: "Italy", region: "Europe", image: "/monuments/dolomites.jpg" },
  { id: "lake-como", name: "Lake Como", country: "Italy", region: "Europe", image: "/monuments/lake-como.jpg" },
  { id: "sistine-chapel", name: "The Sistine Chapel", country: "Vatican City", region: "Europe", image: "/monuments/sistine-chapel.jpg" },
  { id: "pantheon-rome", name: "The Pantheon", country: "Italy", region: "Europe", image: "/monuments/pantheon-rome.jpg" },
  { id: "spanish-steps", name: "The Spanish Steps", country: "Italy", region: "Europe", image: "/monuments/spanish-steps.jpg" },
  { id: "burano", name: "Burano", country: "Italy", region: "Europe", image: "/monuments/burano.jpg" },
  { id: "sicily-etna", name: "Mount Etna", country: "Italy", region: "Europe", image: "/monuments/sicily-etna.jpg" },
  { id: "toledo-spain", name: "Toledo", country: "Spain", region: "Europe", image: "/monuments/toledo-spain.jpg" },
  { id: "seville-cathedral", name: "Seville Cathedral", country: "Spain", region: "Europe", image: "/monuments/seville-cathedral.jpg" },
  { id: "plaza-de-espana", name: "Plaza de España", country: "Spain", region: "Europe", image: "/monuments/plaza-de-espana.jpg" },
  { id: "mezquita-cordoba", name: "The Mezquita of Córdoba", country: "Spain", region: "Europe", image: "/monuments/mezquita-cordoba.jpg" },
  { id: "gaudi-casa-batllo", name: "Casa Batlló", country: "Spain", region: "Europe", image: "/monuments/gaudi-casa-batllo.jpg" },
  { id: "benagil-cave", name: "The Benagil Cave", country: "Portugal", region: "Europe", image: "/monuments/benagil-cave.jpg" },
  { id: "douro-valley", name: "The Douro Valley", country: "Portugal", region: "Europe", image: "/monuments/douro-valley.jpg" },
  { id: "parthenon", name: "The Parthenon", country: "Greece", region: "Europe", image: "/monuments/parthenon.jpg" },
  { id: "delphi", name: "Delphi", country: "Greece", region: "Europe", image: "/monuments/delphi.jpg" },
  { id: "mykonos", name: "Mykonos", country: "Greece", region: "Europe", image: "/monuments/mykonos.jpg" },
  { id: "rhodes-old-town", name: "The Old Town of Rhodes", country: "Greece", region: "Europe", image: "/monuments/rhodes-old-town.jpg" },
  { id: "navagio-beach", name: "Navagio Beach", country: "Greece", region: "Europe", image: "/monuments/navagio-beach.jpg" },
  { id: "windsor-castle", name: "Windsor Castle", country: "United Kingdom", region: "Europe", image: "/monuments/windsor-castle.jpg" },
  { id: "lake-district", name: "The Lake District", country: "United Kingdom", region: "Europe", image: "/monuments/lake-district.jpg" },
  { id: "loch-ness", name: "Loch Ness", country: "United Kingdom", region: "Europe", image: "/monuments/loch-ness.jpg" },
  { id: "york-minster", name: "York Minster", country: "United Kingdom", region: "Europe", image: "/monuments/york-minster.jpg" },
  { id: "bath-roman-baths", name: "The Roman Baths of Bath", country: "United Kingdom", region: "Europe", image: "/monuments/bath-roman-baths.jpg" },
  { id: "snowdonia", name: "Snowdonia", country: "United Kingdom", region: "Europe", image: "/monuments/snowdonia.jpg" },
  { id: "eden-project", name: "The Eden Project", country: "United Kingdom", region: "Europe", image: "/monuments/eden-project.jpg" },
  { id: "dublin-castle", name: "Dublin Castle", country: "Ireland", region: "Europe", image: "/monuments/dublin-castle.jpg" },
  { id: "ring-of-kerry", name: "The Ring of Kerry", country: "Ireland", region: "Europe", image: "/monuments/ring-of-kerry.jpg" },
  { id: "connemara", name: "Connemara National Park", country: "Ireland", region: "Europe", image: "/monuments/connemara.jpg" },
  { id: "keukenhof-gardens", name: "Keukenhof Gardens", country: "Netherlands", region: "Europe", image: "/monuments/keukenhof-gardens.jpg" },
  { id: "zaanse-schans", name: "Zaanse Schans", country: "Netherlands", region: "Europe", image: "/monuments/zaanse-schans.jpg" },
  { id: "rijksmuseum", name: "The Rijksmuseum", country: "Netherlands", region: "Europe", image: "/monuments/rijksmuseum.jpg" },
  { id: "atomium", name: "The Atomium", country: "Belgium", region: "Europe", image: "/monuments/atomium.jpg" },
  { id: "grand-place-brussels", name: "The Grand Place", country: "Belgium", region: "Europe", image: "/monuments/grand-place-brussels.jpg" },
  { id: "bruges-canals", name: "The Canals of Bruges", country: "Belgium", region: "Europe", image: "/monuments/bruges-canals.jpg" },
  { id: "vianden-castle", name: "Vianden Castle", country: "Luxembourg", region: "Europe", image: "/monuments/vianden-castle.jpg" },
  { id: "kronborg-castle", name: "Kronborg Castle", country: "Denmark", region: "Europe", image: "/monuments/kronborg-castle.jpg" },
  { id: "nyhavn", name: "Nyhavn", country: "Denmark", region: "Europe", image: "/monuments/nyhavn.jpg" },
  { id: "tivoli-gardens", name: "Tivoli Gardens", country: "Denmark", region: "Europe", image: "/monuments/tivoli-gardens.jpg" },
  { id: "geirangerfjord", name: "Geirangerfjord", country: "Norway", region: "Europe", image: "/monuments/geirangerfjord.jpg" },
  { id: "lofoten-islands", name: "The Lofoten Islands", country: "Norway", region: "Europe", image: "/monuments/lofoten-islands.jpg" },
  { id: "trolltunga", name: "Trolltunga", country: "Norway", region: "Europe", image: "/monuments/trolltunga.jpg" },
  { id: "preikestolen", name: "Preikestolen", country: "Norway", region: "Europe", image: "/monuments/preikestolen.jpg" },
  { id: "northern-lights-tromso", name: "The Northern Lights over Tromsø", country: "Norway", region: "Europe", image: "/monuments/northern-lights-tromso.jpg" },
  { id: "stockholm-old-town", name: "Gamla Stan", country: "Sweden", region: "Europe", image: "/monuments/stockholm-old-town.jpg" },
  { id: "icehotel-sweden", name: "The Icehotel", country: "Sweden", region: "Europe", image: "/monuments/icehotel-sweden.jpg" },
  { id: "blue-lagoon-iceland", name: "The Blue Lagoon", country: "Iceland", region: "Europe", image: "/monuments/blue-lagoon-iceland.jpg" },
  { id: "gullfoss", name: "Gullfoss", country: "Iceland", region: "Europe", image: "/monuments/gullfoss.jpg" },
  { id: "jokulsarlon", name: "Jökulsárlón", country: "Iceland", region: "Europe", image: "/monuments/jokulsarlon.jpg" },
  { id: "reynisfjara", name: "Reynisfjara Beach", country: "Iceland", region: "Europe", image: "/monuments/reynisfjara.jpg" },
  { id: "seljalandsfoss", name: "Seljalandsfoss", country: "Iceland", region: "Europe", image: "/monuments/seljalandsfoss.jpg" },
  { id: "skogafoss", name: "Skógafoss", country: "Iceland", region: "Europe", image: "/monuments/skogafoss.jpg" },
  { id: "helsinki-cathedral", name: "Helsinki Cathedral", country: "Finland", region: "Europe", image: "/monuments/helsinki-cathedral.jpg" },
  { id: "lapland-santa-village", name: "Santa Claus Village", country: "Finland", region: "Europe", image: "/monuments/lapland-santa-village.jpg" },
  { id: "saimaa-lake", name: "Lake Saimaa", country: "Finland", region: "Europe", image: "/monuments/saimaa-lake.jpg" },
  { id: "red-square", name: "Red Square", country: "Russia", region: "Europe", image: "/monuments/red-square.jpg" },
  { id: "hermitage-museum", name: "The Hermitage Museum", country: "Russia", region: "Europe", image: "/monuments/hermitage-museum.jpg" },
  { id: "peterhof-palace", name: "Peterhof Palace", country: "Russia", region: "Europe", image: "/monuments/peterhof-palace.jpg" },
  { id: "church-of-the-savior-on-blood", name: "The Church of the Savior on Spilled Blood", country: "Russia", region: "Europe", image: "/monuments/church-of-the-savior-on-blood.jpg" },
  { id: "wieliczka-salt-mine", name: "The Wieliczka Salt Mine", country: "Poland", region: "Europe", image: "/monuments/wieliczka-salt-mine.jpg" },
  { id: "krakow-main-square", name: "Kraków's Main Square", country: "Poland", region: "Europe", image: "/monuments/krakow-main-square.jpg" },
  { id: "malbork-castle", name: "Malbork Castle", country: "Poland", region: "Europe", image: "/monuments/malbork-castle.jpg" },
  { id: "buda-castle", name: "Buda Castle", country: "Hungary", region: "Europe", image: "/monuments/buda-castle.jpg" },
  { id: "hungarian-parliament", name: "The Hungarian Parliament Building", country: "Hungary", region: "Europe", image: "/monuments/hungarian-parliament.jpg" },
  { id: "lake-balaton", name: "Lake Balaton", country: "Hungary", region: "Europe", image: "/monuments/lake-balaton.jpg" },
  { id: "szechenyi-baths", name: "The Széchenyi Thermal Bath", country: "Hungary", region: "Europe", image: "/monuments/szechenyi-baths.jpg" },
  { id: "bran-castle", name: "Bran Castle", country: "Romania", region: "Europe", image: "/monuments/bran-castle.jpg" },
  { id: "peles-castle", name: "Peleș Castle", country: "Romania", region: "Europe", image: "/monuments/peles-castle.jpg" },
  { id: "transfagarasan-highway", name: "The Transfăgărășan Highway", country: "Romania", region: "Europe", image: "/monuments/transfagarasan-highway.jpg" },
  { id: "rila-monastery", name: "Rila Monastery", country: "Bulgaria", region: "Europe", image: "/monuments/rila-monastery.jpg" },
  { id: "plovdiv-old-town", name: "Plovdiv's Old Town", country: "Bulgaria", region: "Europe", image: "/monuments/plovdiv-old-town.jpg" },
  { id: "belgrade-fortress", name: "Belgrade Fortress", country: "Serbia", region: "Europe", image: "/monuments/belgrade-fortress.jpg" },
  { id: "lake-bohinj", name: "Lake Bohinj", country: "Slovenia", region: "Europe", image: "/monuments/lake-bohinj.jpg" },
  { id: "predjama-castle", name: "Predjama Castle", country: "Slovenia", region: "Europe", image: "/monuments/predjama-castle.jpg" },
  { id: "postojna-cave", name: "Postojna Cave", country: "Slovenia", region: "Europe", image: "/monuments/postojna-cave.jpg" },
  { id: "krka-national-park", name: "Krka National Park", country: "Croatia", region: "Europe", image: "/monuments/krka-national-park.jpg" },
  { id: "split-diocletian-palace", name: "Diocletian's Palace", country: "Croatia", region: "Europe", image: "/monuments/split-diocletian-palace.jpg" },
  { id: "hvar-island", name: "Hvar", country: "Croatia", region: "Europe", image: "/monuments/hvar-island.jpg" },
  { id: "vintgar-gorge", name: "Vintgar Gorge", country: "Slovenia", region: "Europe", image: "/monuments/vintgar-gorge.jpg" },
  { id: "lucerne-chapel-bridge", name: "The Chapel Bridge", country: "Switzerland", region: "Europe", image: "/monuments/lucerne-chapel-bridge.jpg" },
  { id: "jungfraujoch", name: "Jungfraujoch", country: "Switzerland", region: "Europe", image: "/monuments/jungfraujoch.jpg" },
  { id: "lake-geneva", name: "Lake Geneva", country: "Switzerland", region: "Europe", image: "/monuments/lake-geneva.jpg" },
  { id: "interlaken", name: "Interlaken", country: "Switzerland", region: "Europe", image: "/monuments/interlaken.jpg" },
  { id: "rhine-falls", name: "The Rhine Falls", country: "Switzerland", region: "Europe", image: "/monuments/rhine-falls.jpg" },
  { id: "salzburg-fortress", name: "Hohensalzburg Fortress", country: "Austria", region: "Europe", image: "/monuments/salzburg-fortress.jpg" },
  { id: "melk-abbey", name: "Melk Abbey", country: "Austria", region: "Europe", image: "/monuments/melk-abbey.jpg" },
  { id: "vienna-state-opera", name: "The Vienna State Opera", country: "Austria", region: "Europe", image: "/monuments/vienna-state-opera.jpg" },
  { id: "tallinn-old-town", name: "Tallinn's Old Town", country: "Estonia", region: "Europe", image: "/monuments/tallinn-old-town.jpg" },
  { id: "riga-old-town", name: "Riga's Old Town", country: "Latvia", region: "Europe", image: "/monuments/riga-old-town.jpg" },
  { id: "trakai-castle", name: "Trakai Island Castle", country: "Lithuania", region: "Europe", image: "/monuments/trakai-castle.jpg" },
  { id: "curonian-spit", name: "The Curonian Spit", country: "Lithuania", region: "Europe", image: "/monuments/curonian-spit.jpg" },
  // Africa (expansion)
  { id: "marrakech-medina", name: "The Medina of Marrakech", country: "Morocco", region: "Africa", image: "/monuments/marrakech-medina.jpg" },
  { id: "ait-benhaddou", name: "Aït Benhaddou", country: "Morocco", region: "Africa", image: "/monuments/ait-benhaddou.jpg" },
  { id: "atlas-mountains", name: "The Atlas Mountains", country: "Morocco", region: "Africa", image: "/monuments/atlas-mountains.jpg" },
  { id: "essaouira", name: "Essaouira", country: "Morocco", region: "Africa", image: "/monuments/essaouira.jpg" },
  { id: "tunis-medina", name: "The Medina of Tunis", country: "Tunisia", region: "Africa", image: "/monuments/tunis-medina.jpg" },
  { id: "el-djem-amphitheatre", name: "The Amphitheatre of El Jem", country: "Tunisia", region: "Africa", image: "/monuments/el-djem-amphitheatre.jpg" },
  { id: "sidi-bou-said", name: "Sidi Bou Said", country: "Tunisia", region: "Africa", image: "/monuments/sidi-bou-said.jpg" },
  { id: "leptis-magna", name: "Leptis Magna", country: "Libya", region: "Africa", image: "/monuments/leptis-magna.jpg" },
  { id: "siwa-oasis", name: "Siwa Oasis", country: "Egypt", region: "Africa", image: "/monuments/siwa-oasis.jpg" },
  { id: "aswan-nile", name: "The Nile at Aswan", country: "Egypt", region: "Africa", image: "/monuments/aswan-nile.jpg" },
  { id: "alexandria-library", name: "The Bibliotheca Alexandrina", country: "Egypt", region: "Africa", image: "/monuments/alexandria-library.jpg" },
  { id: "red-sea-egypt", name: "The Red Sea Riviera", country: "Egypt", region: "Africa", image: "/monuments/red-sea-egypt.jpg" },
  { id: "simien-mountains", name: "The Simien Mountains", country: "Ethiopia", region: "Africa", image: "/monuments/simien-mountains.jpg" },
  { id: "blue-nile-falls", name: "The Blue Nile Falls", country: "Ethiopia", region: "Africa", image: "/monuments/blue-nile-falls.jpg" },
  { id: "aksum-obelisks", name: "The Obelisks of Aksum", country: "Ethiopia", region: "Africa", image: "/monuments/aksum-obelisks.jpg" },
  { id: "nairobi-national-park", name: "Nairobi National Park", country: "Kenya", region: "Africa", image: "/monuments/nairobi-national-park.jpg" },
  { id: "lake-nakuru", name: "Lake Nakuru", country: "Kenya", region: "Africa", image: "/monuments/lake-nakuru.jpg" },
  { id: "lamu-old-town", name: "Lamu Old Town", country: "Kenya", region: "Africa", image: "/monuments/lamu-old-town.jpg" },
  { id: "virunga-national-park", name: "Virunga National Park", country: "Democratic Republic of the Congo", region: "Africa", image: "/monuments/virunga-national-park.jpg" },
  { id: "volcanoes-national-park", name: "Volcanoes National Park", country: "Rwanda", region: "Africa", image: "/monuments/volcanoes-national-park.jpg" },
  { id: "lake-kivu", name: "Lake Kivu", country: "Rwanda", region: "Africa", image: "/monuments/lake-kivu.jpg" },
  { id: "bwindi-forest", name: "Bwindi Impenetrable Forest", country: "Uganda", region: "Africa", image: "/monuments/bwindi-forest.jpg" },
  { id: "murchison-falls", name: "Murchison Falls", country: "Uganda", region: "Africa", image: "/monuments/murchison-falls.jpg" },
  { id: "source-of-the-nile", name: "The Source of the Nile", country: "Uganda", region: "Africa", image: "/monuments/source-of-the-nile.jpg" },
  { id: "gombe-stream", name: "Gombe Stream National Park", country: "Tanzania", region: "Africa", image: "/monuments/gombe-stream.jpg" },
  { id: "mafia-island", name: "Mafia Island", country: "Tanzania", region: "Africa", image: "/monuments/mafia-island.jpg" },
  { id: "skeleton-coast", name: "The Skeleton Coast", country: "Namibia", region: "Africa", image: "/monuments/skeleton-coast.jpg" },
  { id: "sossusvlei", name: "Sossusvlei", country: "Namibia", region: "Africa", image: "/monuments/sossusvlei.jpg" },
  { id: "etosha-national-park", name: "Etosha National Park", country: "Namibia", region: "Africa", image: "/monuments/etosha-national-park.jpg" },
  { id: "fish-river-canyon", name: "Fish River Canyon", country: "Namibia", region: "Africa", image: "/monuments/fish-river-canyon.jpg" },
  { id: "kruger-national-park", name: "Kruger National Park", country: "South Africa", region: "Africa", image: "/monuments/kruger-national-park.jpg" },
  { id: "blyde-river-canyon", name: "Blyde River Canyon", country: "South Africa", region: "Africa", image: "/monuments/blyde-river-canyon.jpg" },
  { id: "drakensberg-mountains", name: "The Drakensberg Mountains", country: "South Africa", region: "Africa", image: "/monuments/drakensberg-mountains.jpg" },
  { id: "boulders-beach", name: "Boulders Beach", country: "South Africa", region: "Africa", image: "/monuments/boulders-beach.jpg" },
  { id: "chobe-national-park", name: "Chobe National Park", country: "Botswana", region: "Africa", image: "/monuments/chobe-national-park.jpg" },
  { id: "tsodilo-hills", name: "The Tsodilo Hills", country: "Botswana", region: "Africa", image: "/monuments/tsodilo-hills.jpg" },
  { id: "mosi-oa-tunya", name: "Mosi-oa-Tunya National Park", country: "Zambia", region: "Africa", image: "/monuments/mosi-oa-tunya.jpg" },
  { id: "south-luangwa", name: "South Luangwa National Park", country: "Zambia", region: "Africa", image: "/monuments/south-luangwa.jpg" },
  { id: "great-zimbabwe", name: "The Ruins of Great Zimbabwe", country: "Zimbabwe", region: "Africa", image: "/monuments/great-zimbabwe.jpg" },
  { id: "hwange-national-park", name: "Hwange National Park", country: "Zimbabwe", region: "Africa", image: "/monuments/hwange-national-park.jpg" },
  { id: "lake-malawi", name: "Lake Malawi", country: "Malawi", region: "Africa", image: "/monuments/lake-malawi.jpg" },
  { id: "ile-sainte-marie", name: "Île Sainte-Marie", country: "Madagascar", region: "Africa", image: "/monuments/ile-sainte-marie.jpg" },
  { id: "avenue-of-the-baobabs", name: "The Avenue of the Baobabs", country: "Madagascar", region: "Africa", image: "/monuments/avenue-of-the-baobabs.jpg" },
  { id: "tsingy-de-bemaraha", name: "Tsingy de Bemaraha", country: "Madagascar", region: "Africa", image: "/monuments/tsingy-de-bemaraha.jpg" },
  { id: "anse-source-dargent", name: "Anse Source d'Argent", country: "Seychelles", region: "Africa", image: "/monuments/anse-source-dargent.jpg" },
  { id: "aldabra-atoll", name: "Aldabra Atoll", country: "Seychelles", region: "Africa", image: "/monuments/aldabra-atoll.jpg" },
  { id: "black-river-gorges", name: "Black River Gorges National Park", country: "Mauritius", region: "Africa", image: "/monuments/black-river-gorges.jpg" },
  { id: "le-morne-brabant", name: "Le Morne Brabant", country: "Mauritius", region: "Africa", image: "/monuments/le-morne-brabant.jpg" },
  { id: "cape-verde-fogo-volcano", name: "The Fogo Volcano", country: "Cape Verde", region: "Africa", image: "/monuments/cape-verde-fogo-volcano.jpg" },
  { id: "lake-retba", name: "Lake Retba", country: "Senegal", region: "Africa", image: "/monuments/lake-retba.jpg" },
  { id: "goree-island", name: "Gorée Island", country: "Senegal", region: "Africa", image: "/monuments/goree-island.jpg" },
  { id: "cape-coast-castle", name: "Cape Coast Castle", country: "Ghana", region: "Africa", image: "/monuments/cape-coast-castle.jpg" },
  { id: "lake-volta", name: "Lake Volta", country: "Ghana", region: "Africa", image: "/monuments/lake-volta.jpg" },
  { id: "osun-sacred-grove", name: "The Osun-Osogbo Sacred Grove", country: "Nigeria", region: "Africa", image: "/monuments/osun-sacred-grove.jpg" },
  { id: "zuma-rock", name: "Zuma Rock", country: "Nigeria", region: "Africa", image: "/monuments/zuma-rock.jpg" },
  { id: "kasbah-of-algiers", name: "The Kasbah of Algiers", country: "Algeria", region: "Africa", image: "/monuments/kasbah-of-algiers.jpg" },
  { id: "vredefort-dome", name: "The Vredefort Dome", country: "South Africa", region: "Africa", image: "/monuments/vredefort-dome.jpg" },
  { id: "okavango-panhandle", name: "The Okavango Panhandle", country: "Botswana", region: "Africa", image: "/monuments/okavango-panhandle.jpg" },
  // Americas (expansion)
  { id: "zion-national-park", name: "Zion National Park", country: "United States", region: "Americas", image: "/monuments/zion-national-park.jpg" },
  { id: "bryce-canyon", name: "Bryce Canyon National Park", country: "United States", region: "Americas", image: "/monuments/bryce-canyon.jpg" },
  { id: "arches-national-park", name: "Arches National Park", country: "United States", region: "Americas", image: "/monuments/arches-national-park.jpg" },
  { id: "glacier-national-park", name: "Glacier National Park", country: "United States", region: "Americas", image: "/monuments/glacier-national-park.jpg" },
  { id: "grand-teton", name: "Grand Teton National Park", country: "United States", region: "Americas", image: "/monuments/grand-teton.jpg" },
  { id: "death-valley", name: "Death Valley National Park", country: "United States", region: "Americas", image: "/monuments/death-valley.jpg" },
  { id: "crater-lake", name: "Crater Lake National Park", country: "United States", region: "Americas", image: "/monuments/crater-lake.jpg" },
  { id: "redwood-national-park", name: "Redwood National Park", country: "United States", region: "Americas", image: "/monuments/redwood-national-park.jpg" },
  { id: "sequoia-national-park", name: "Sequoia National Park", country: "United States", region: "Americas", image: "/monuments/sequoia-national-park.jpg" },
  { id: "joshua-tree", name: "Joshua Tree National Park", country: "United States", region: "Americas", image: "/monuments/joshua-tree.jpg" },
  { id: "everglades", name: "Everglades National Park", country: "United States", region: "Americas", image: "/monuments/everglades.jpg" },
  { id: "acadia-national-park", name: "Acadia National Park", country: "United States", region: "Americas", image: "/monuments/acadia-national-park.jpg" },
  { id: "mount-rainier", name: "Mount Rainier", country: "United States", region: "Americas", image: "/monuments/mount-rainier.jpg" },
  { id: "denali", name: "Denali", country: "United States", region: "Americas", image: "/monuments/denali.jpg" },
  { id: "horseshoe-bend", name: "Horseshoe Bend", country: "United States", region: "Americas", image: "/monuments/horseshoe-bend.jpg" },
  { id: "monument-valley", name: "Monument Valley", country: "United States", region: "Americas", image: "/monuments/monument-valley.jpg" },
  { id: "french-quarter-mardi-gras", name: "Mardi Gras in New Orleans", country: "United States", region: "Americas", image: "/monuments/french-quarter-mardi-gras.jpg" },
  { id: "biltmore-estate", name: "The Biltmore Estate", country: "United States", region: "Americas", image: "/monuments/biltmore-estate.jpg" },
  { id: "griffith-observatory", name: "The Griffith Observatory", country: "United States", region: "Americas", image: "/monuments/griffith-observatory.jpg" },
  { id: "pike-place-market", name: "Pike Place Market", country: "United States", region: "Americas", image: "/monuments/pike-place-market.jpg" },
  { id: "golden-gate-park", name: "Golden Gate Park", country: "United States", region: "Americas", image: "/monuments/golden-gate-park.jpg" },
  { id: "central-park", name: "Central Park", country: "United States", region: "Americas", image: "/monuments/central-park.jpg" },
  { id: "disney-world-castle", name: "Cinderella Castle at Walt Disney World", country: "United States", region: "Americas", image: "/monuments/disney-world-castle.jpg" },
  { id: "liberty-bell", name: "The Liberty Bell", country: "United States", region: "Americas", image: "/monuments/liberty-bell.jpg" },
  { id: "mall-of-america", name: "The Mall of America", country: "United States", region: "Americas", image: "/monuments/mall-of-america.jpg" },
  { id: "willis-tower", name: "The Willis Tower", country: "United States", region: "Americas", image: "/monuments/willis-tower.jpg" },
  { id: "key-west", name: "Key West", country: "United States", region: "Americas", image: "/monuments/key-west.jpg" },
  { id: "national-mall", name: "The National Mall", country: "United States", region: "Americas", image: "/monuments/national-mall.jpg" },
  { id: "jefferson-memorial", name: "The Jefferson Memorial", country: "United States", region: "Americas", image: "/monuments/jefferson-memorial.jpg" },
  { id: "quebec-city-old-town", name: "Old Québec", country: "Canada", region: "Americas", image: "/monuments/quebec-city-old-town.jpg" },
  { id: "jasper-national-park", name: "Jasper National Park", country: "Canada", region: "Americas", image: "/monuments/jasper-national-park.jpg" },
  { id: "peggys-cove", name: "Peggy's Cove", country: "Canada", region: "Americas", image: "/monuments/peggys-cove.jpg" },
  { id: "parliament-hill-ottawa", name: "Parliament Hill", country: "Canada", region: "Americas", image: "/monuments/parliament-hill-ottawa.jpg" },
  { id: "bay-of-fundy", name: "The Bay of Fundy", country: "Canada", region: "Americas", image: "/monuments/bay-of-fundy.jpg" },
  { id: "toronto-cn-skyline", name: "The Toronto Skyline", country: "Canada", region: "Americas", image: "/monuments/toronto-cn-skyline.jpg" },
  { id: "cenote-ik-kil", name: "Ik Kil Cenote", country: "Mexico", region: "Americas", image: "/monuments/cenote-ik-kil.jpg" },
  { id: "cabo-san-lucas", name: "Cabo San Lucas", country: "Mexico", region: "Americas", image: "/monuments/cabo-san-lucas.jpg" },
  { id: "guanajuato", name: "Guanajuato", country: "Mexico", region: "Americas", image: "/monuments/guanajuato.jpg" },
  { id: "palenque", name: "Palenque", country: "Mexico", region: "Americas", image: "/monuments/palenque.jpg" },
  { id: "xcaret-park", name: "Xcaret Park", country: "Mexico", region: "Americas", image: "/monuments/xcaret-park.jpg" },
  { id: "copan-ruins", name: "The Ruins of Copán", country: "Honduras", region: "Americas", image: "/monuments/copan-ruins.jpg" },
  { id: "arenal-volcano", name: "Arenal Volcano", country: "Costa Rica", region: "Americas", image: "/monuments/arenal-volcano.jpg" },
  { id: "monteverde-cloud-forest", name: "The Monteverde Cloud Forest", country: "Costa Rica", region: "Americas", image: "/monuments/monteverde-cloud-forest.jpg" },
  { id: "tikal", name: "Tikal", country: "Guatemala", region: "Americas", image: "/monuments/tikal.jpg" },
  { id: "lake-atitlan", name: "Lake Atitlán", country: "Guatemala", region: "Americas", image: "/monuments/lake-atitlan.jpg" },
  { id: "antigua-guatemala", name: "Antigua Guatemala", country: "Guatemala", region: "Americas", image: "/monuments/antigua-guatemala.jpg" },
  { id: "corcovado-national-park", name: "Corcovado National Park", country: "Costa Rica", region: "Americas", image: "/monuments/corcovado-national-park.jpg" },
  { id: "blue-hole-belize", name: "The Great Blue Hole", country: "Belize", region: "Americas", image: "/monuments/blue-hole-belize.jpg" },
  { id: "christ-of-the-abyss", name: "Christ of the Abyss", country: "Cuba", region: "Americas", image: "/monuments/christ-of-the-abyss.jpg" },
  { id: "varadero-beach", name: "Varadero Beach", country: "Cuba", region: "Americas", image: "/monuments/varadero-beach.jpg" },
  { id: "trinidad-cuba", name: "Trinidad, Cuba", country: "Cuba", region: "Americas", image: "/monuments/trinidad-cuba.jpg" },
  { id: "dunns-river-falls", name: "Dunn's River Falls", country: "Jamaica", region: "Americas", image: "/monuments/dunns-river-falls.jpg" },
  { id: "blue-mountains-jamaica", name: "The Blue Mountains", country: "Jamaica", region: "Americas", image: "/monuments/blue-mountains-jamaica.jpg" },
  { id: "angel-falls", name: "Angel Falls", country: "Venezuela", region: "Americas", image: "/monuments/angel-falls.jpg" },
  { id: "mount-roraima", name: "Mount Roraima", country: "Venezuela", region: "Americas", image: "/monuments/mount-roraima.jpg" },
  { id: "cano-cristales", name: "Caño Cristales", country: "Colombia", region: "Americas", image: "/monuments/cano-cristales.jpg" },
  { id: "tayrona-national-park", name: "Tayrona National Park", country: "Colombia", region: "Americas", image: "/monuments/tayrona-national-park.jpg" },
  { id: "salento-colombia", name: "Salento's Cocora Valley", country: "Colombia", region: "Americas", image: "/monuments/salento-colombia.jpg" },
  { id: "quito-old-town", name: "Quito's Old Town", country: "Ecuador", region: "Americas", image: "/monuments/quito-old-town.jpg" },
  { id: "cotopaxi", name: "Cotopaxi", country: "Ecuador", region: "Americas", image: "/monuments/cotopaxi.jpg" },
  { id: "nazca-lines", name: "The Nazca Lines", country: "Peru", region: "Americas", image: "/monuments/nazca-lines.jpg" },
  { id: "rainbow-mountain-peru", name: "Rainbow Mountain", country: "Peru", region: "Americas", image: "/monuments/rainbow-mountain-peru.jpg" },
  { id: "lake-titicaca", name: "Lake Titicaca", country: "Peru", region: "Americas", image: "/monuments/lake-titicaca.jpg" },
  { id: "colca-canyon", name: "Colca Canyon", country: "Peru", region: "Americas", image: "/monuments/colca-canyon.jpg" },
  { id: "sacred-valley-peru", name: "The Sacred Valley", country: "Peru", region: "Americas", image: "/monuments/sacred-valley-peru.jpg" },
  { id: "uyuni-salt-flats-mirror", name: "The Uyuni Salt Flats Mirror Effect", country: "Bolivia", region: "Americas", image: "/monuments/uyuni-salt-flats-mirror.jpg" },
  { id: "death-road-bolivia", name: "The Yungas Road", country: "Bolivia", region: "Americas", image: "/monuments/death-road-bolivia.jpg" },
  { id: "pantanal", name: "The Pantanal", country: "Brazil", region: "Americas", image: "/monuments/pantanal.jpg" },
  { id: "fernando-de-noronha", name: "Fernando de Noronha", country: "Brazil", region: "Americas", image: "/monuments/fernando-de-noronha.jpg" },
  { id: "lencois-maranhenses", name: "Lençóis Maranhenses National Park", country: "Brazil", region: "Americas", image: "/monuments/lencois-maranhenses.jpg" },
  { id: "sugarloaf-mountain", name: "Sugarloaf Mountain", country: "Brazil", region: "Americas", image: "/monuments/sugarloaf-mountain.jpg" },
  { id: "ipanema-beach", name: "Ipanema Beach", country: "Brazil", region: "Americas", image: "/monuments/ipanema-beach.jpg" },
  { id: "chapada-diamantina", name: "Chapada Diamantina National Park", country: "Brazil", region: "Americas", image: "/monuments/chapada-diamantina.jpg" },
  { id: "ushuaia", name: "Ushuaia", country: "Argentina", region: "Americas", image: "/monuments/ushuaia.jpg" },
  { id: "bariloche", name: "Bariloche", country: "Argentina", region: "Americas", image: "/monuments/bariloche.jpg" },
  { id: "quebrada-de-humahuaca", name: "Quebrada de Humahuaca", country: "Argentina", region: "Americas", image: "/monuments/quebrada-de-humahuaca.jpg" },
  { id: "valle-de-la-luna", name: "Valle de la Luna", country: "Chile", region: "Americas", image: "/monuments/valle-de-la-luna.jpg" },
  { id: "la-boca-buenos-aires", name: "La Boca", country: "Argentina", region: "Americas", image: "/monuments/la-boca-buenos-aires.jpg" },
  // Oceania (expansion)
  { id: "blue-mountains-australia", name: "The Blue Mountains", country: "Australia", region: "Oceania", image: "/monuments/blue-mountains-australia.jpg" },
  { id: "whitehaven-beach", name: "Whitehaven Beach", country: "Australia", region: "Oceania", image: "/monuments/whitehaven-beach.jpg" },
  { id: "kakadu-national-park", name: "Kakadu National Park", country: "Australia", region: "Oceania", image: "/monuments/kakadu-national-park.jpg" },
  { id: "fraser-island", name: "K'gari (Fraser Island)", country: "Australia", region: "Oceania", image: "/monuments/fraser-island.jpg" },
  { id: "great-ocean-road", name: "The Great Ocean Road", country: "Australia", region: "Oceania", image: "/monuments/great-ocean-road.jpg" },
  { id: "the-pinnacles-australia", name: "The Pinnacles", country: "Australia", region: "Oceania", image: "/monuments/the-pinnacles-australia.jpg" },
  { id: "wave-rock", name: "Wave Rock", country: "Australia", region: "Oceania", image: "/monuments/wave-rock.jpg" },
  { id: "grampians-national-park", name: "Grampians National Park", country: "Australia", region: "Oceania", image: "/monuments/grampians-national-park.jpg" },
  { id: "freycinet-national-park", name: "Freycinet National Park", country: "Australia", region: "Oceania", image: "/monuments/freycinet-national-park.jpg" },
  { id: "cradle-mountain", name: "Cradle Mountain", country: "Australia", region: "Oceania", image: "/monuments/cradle-mountain.jpg" },
  { id: "ningaloo-reef", name: "Ningaloo Reef", country: "Australia", region: "Oceania", image: "/monuments/ningaloo-reef.jpg" },
  { id: "federation-square", name: "Federation Square", country: "Australia", region: "Oceania", image: "/monuments/federation-square.jpg" },
  { id: "scenic-world-katoomba", name: "The Three Sisters", country: "Australia", region: "Oceania", image: "/monuments/scenic-world-katoomba.jpg" },
  { id: "purnululu-bungle-bungle", name: "The Bungle Bungle Range", country: "Australia", region: "Oceania", image: "/monuments/purnululu-bungle-bungle.jpg" },
  { id: "lake-hillier", name: "Lake Hillier", country: "Australia", region: "Oceania", image: "/monuments/lake-hillier.jpg" },
  { id: "nambung-national-park", name: "Nambung National Park", country: "Australia", region: "Oceania", image: "/monuments/nambung-national-park.jpg" },
  { id: "tasmania-wineglass-bay", name: "Wineglass Bay", country: "Australia", region: "Oceania", image: "/monuments/tasmania-wineglass-bay.jpg" },
  { id: "fiordland-national-park", name: "Fiordland National Park", country: "New Zealand", region: "Oceania", image: "/monuments/fiordland-national-park.jpg" },
  { id: "lake-tekapo", name: "Lake Tekapo", country: "New Zealand", region: "Oceania", image: "/monuments/lake-tekapo.jpg" },
  { id: "franz-josef-glacier", name: "The Franz Josef Glacier", country: "New Zealand", region: "Oceania", image: "/monuments/franz-josef-glacier.jpg" },
  { id: "abel-tasman-national-park", name: "Abel Tasman National Park", country: "New Zealand", region: "Oceania", image: "/monuments/abel-tasman-national-park.jpg" },
  { id: "cathedral-cove", name: "Cathedral Cove", country: "New Zealand", region: "Oceania", image: "/monuments/cathedral-cove.jpg" },
  { id: "mount-cook", name: "Aoraki / Mount Cook", country: "New Zealand", region: "Oceania", image: "/monuments/mount-cook.jpg" },
  { id: "rotorua-geysers", name: "The Rotorua Geysers", country: "New Zealand", region: "Oceania", image: "/monuments/rotorua-geysers.jpg" },
  { id: "wai-o-tapu", name: "Wai-O-Tapu", country: "New Zealand", region: "Oceania", image: "/monuments/wai-o-tapu.jpg" },
  { id: "napier-art-deco", name: "Napier's Art Deco District", country: "New Zealand", region: "Oceania", image: "/monuments/napier-art-deco.jpg" },
  { id: "moeraki-boulders", name: "The Moeraki Boulders", country: "New Zealand", region: "Oceania", image: "/monuments/moeraki-boulders.jpg" },
  { id: "aitutaki-lagoon", name: "Aitutaki Lagoon", country: "Cook Islands", region: "Oceania", image: "/monuments/aitutaki-lagoon.jpg" },
  { id: "champagne-pool-nz", name: "The Champagne Pool", country: "New Zealand", region: "Oceania", image: "/monuments/champagne-pool-nz.jpg" },
  { id: "nan-madol", name: "Nan Madol", country: "Micronesia", region: "Oceania", image: "/monuments/nan-madol.jpg" },
  { id: "palau-jellyfish-lake", name: "Jellyfish Lake", country: "Palau", region: "Oceania", image: "/monuments/palau-jellyfish-lake.jpg" },
];

export function monumentById(id: string): MonumentDef | undefined {
  return MONUMENTS.find((m) => m.id === id);
}

export const UPLIFTING_QUOTES: string[] = [
  "Some things take time to come together — and that's exactly as it should be.",
  "Every piece you place is still progress, even the ones that take a few tries.",
  "There's no rush here. The view is just as beautiful at your own pace.",
  "What looks scattered now is closer to whole than you think.",
  "Patience isn't waiting — it's building something worth seeing.",
  "You don't have to rush toward finished. Finished will meet you when it's ready.",
  "Small, steady moves are still the ones that build something lasting.",
  "It's okay if it takes longer than you expected. It still came together.",
  "Some of the best things in the world were built one careful piece at a time.",
  "You showed up for something slow and quiet today. That counts for a lot.",
  "A little bit of care, placed again and again, becomes something whole.",
  "Nothing here was rushed, and neither should you be.",
  "The pieces fit eventually. They always do, when you give them room to.",
  "You didn't need to be fast. You only needed to keep going.",
  "This came together because you were willing to sit with it a while.",
  "Not every kind of progress feels urgent — some of it just feels peaceful.",
  "You built this the same way most good things get built: slowly, and on purpose.",
  "Take a breath. What you just finished, you finished at exactly the right pace.",
  "It's a good kind of quiet, the one that comes after finishing something gently.",
  "Some journeys are measured in miles. Others, in pieces fit together with care.",
];

export function randomQuote(): string {
  return UPLIFTING_QUOTES[Math.floor(Math.random() * UPLIFTING_QUOTES.length)];
}
